##
# This almost works.  There's a weird dependency issue with Sqlalchemy.  Come back to this after
# Pydanict and SQLalchemy are updated
##

# ------------------------------
# Stage 1: Build
# ------------------------------
FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim AS builder
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy

# Disable Python downloads, because we want to use the system interpreter
# across both images. If using a managed Python version, it needs to be
# copied from the build image into the final image; see `standalone.Dockerfile`
# for an example.
ENV UV_PYTHON_DOWNLOADS=0

# Install system dependencies and pipenv
RUN apt update && apt upgrade -y && apt install -y --no-install-recommends \
    build-essential \
    curl \
    libtool \
    autoconf \
    automake \
    pkg-config \
    zlib1g-dev \
    python3-dev \
    ca-certificates \
    git \
    python3-pip \
 && apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

#COPY pyproject.toml uv.lock ./
#RUN uv pip freeze > requirements.txt && pip wheel --wheel-dir=/wheels -r requirements.txt
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --no-dev

COPY . /app
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-dev

# Then, use a final image without uv
FROM python:3.13-slim-bookworm AS base
# It is important to use the image that matches the builder, as the path to the
# Python executable must be the same, e.g., using `python:3.11-slim-bookworm`
# will fail.

RUN adduser --disabled-password --gecos '' app

WORKDIR /app

## Copy infrustructure scripts
# Application scripts
COPY --chown=app:app --chmod=775 ./compose/fastapi/entrypoint /fastapi-entrypoint

# Copy to fastapi-start and fastapi-start-datadog to not break current ECS task config
COPY --chown=app:app --chmod=775 ./compose/fastapi/start-backend-datadog /start-backend-datadog
COPY --chown=app:app --chmod=775 ./compose/fastapi/start-backend-datadog /fastapi-start-datadog

# Migration script
COPY --chown=app:app --chmod=775 ./compose/fastapi/migrate /fastapi-migrate

# ECS
COPY --chown=app:app --chmod=775 ./compose/fastapi/ecs-start /ecs-start
COPY --chown=app:app --chmod=775 ./compose/fastapi/ecs-start-feature /ecs-start-feature

# Scheduler and worker
COPY --chmod=775 --chown=app:app ./compose/fastapi/start-worker /start-worker
COPY --chmod=775 --chown=app:app ./compose/fastapi/start-scheduler /start-scheduler

# Copy the application from the builder
COPY --from=builder --chown=app:app /app /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH="src/"

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

USER app

# Run the FastAPI application by default
#CMD ["fastapi", "dev", "--host", "0.0.0.0", "/app/src/uv_docker_example"]
# These are down here to prevent cache busting
ARG DD_GIT_REPOSITORY_URL
ARG DD_GIT_COMMIT_SHA
ENV DD_GIT_REPOSITORY_URL=${DD_GIT_REPOSITORY_URL}
ENV DD_GIT_COMMIT_SHA=${DD_GIT_COMMIT_SHA}

FROM base AS fargate
# TODO Fargate still can't run as the non-priveleged user.  Likely due to old bind mounts.
USER root

VOLUME ["/tmp"]
VOLUME ["/app/uploads"]

FROM base AS app
# This is a hack to allow Fargate to exist since docker will build the last defined target if none is specified
EXPOSE 8000


