#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

redis_ready() {
python << END
import asyncio
import sys
import os

from aioredis import from_url
from config import settings
from infrastructure.logger import logger

client = from_url(url=settings.redis.url)

try:
    asyncio.run(client.echo("Hello"))
except ConnectionError as e:
    logger.error(f"Failed to connect to redis {e}")
    sys.exit(-1)
sys.exit(0)

END
}

rabbit_ready() {
python << END
import asyncio
import sys
import os

import aio_pika
from config import settings
from aiormq.exceptions import AMQPConnectionError
from infrastructure.logger import logger

try:
    asyncio.run(aio_pika.connect_robust(url=settings.rabbitmq.url))
except AMQPConnectionError as e:
    logger.error(f"Failed to connect to rabbit {e}")
    sys.exit(-1)

sys.exit(0)

END
}

until redis_ready; do
  >&2 echo 'Waiting for Redis to become available...'
  sleep 1
done
>&2 echo '>>> Redis is available <<<'

until rabbit_ready; do
  >&2 echo 'Waiting for RabbitMQ to become available...'
  sleep 1
done
>&2 echo '>>> RabbitMQ is available <<<'

exec "$@"
