#!/bin/bash

# Fargate does not have the metadata service, this will fail there but that's ok. When unset it uses the
# default which will work properly with the sidecar.
TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600") && \
  export DD_AGENT_HOST=$(curl http://169.254.169.254/latest/meta-data/local-ipv4 -H "X-aws-ec2-metadata-token: $TOKEN")

set -o errexit
set -o pipefail
set -o nounset

# https://www.uvicorn.org/settings/
export UVICORN_HOST="0.0.0.0"
export UVICORN_PORT=80

export LOG_JSON_FORMAT=true
export DD_TRACE_ENABLED=true

uvicorn main:app \
  --host ${UVICORN_HOST} --port ${UVICORN_PORT} \
  --reload --proxy-headers \
  --log-config uvicorn_disable_logging.json
