#!/bin/bash

if [ "${DD_TRACE_ENABLED}" == "true" ]; then
  export LOG_JSON_FORMAT=true
  TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" --connect-timeout 10 --no-progress-meter) && \
    export DD_AGENT_HOST=$(curl http://169.254.169.254/latest/meta-data/local-ipv4 -H "X-aws-ec2-metadata-token: $TOKEN" --connect-timeout 10 --no-progress-meter)
fi

echo "STARTING APP..."

set -o errexit
set -o pipefail
set -o nounset


# https://www.uvicorn.org/settings/
export UVICORN_HOST="0.0.0.0"
export UVICORN_PORT=80

uvicorn main:app \
  --host ${UVICORN_HOST} --port ${UVICORN_PORT} \
  --reload --proxy-headers \
  --log-config uvicorn_disable_logging.json
