#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# https://www.uvicorn.org/settings/
export UVICORN_HOST="0.0.0.0"
export UVICORN_PORT=80

#opentelemetry-instrument \
#    --logs_exporter otlp \
#    uvicorn src.main:app --reload --host ${UVICORN_HOST} --port ${UVICORN_PORT} --proxy-headers


uvicorn src.main:app --reload --host ${UVICORN_HOST} --port ${UVICORN_PORT} --proxy-headers
