Parameters:
    App:
        Type: String
    Env:
        Type: String
    Name:
        Type: String


Resources:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    Description: Grant access to S3
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: S3Read
          Effect: Allow
          Action:
            - "s3:ListBucket"
            - "s3:AbortMultipartUpload"
            - "s3:ListMultipartUploadParts"
            - "s3:ListBucketMultipartUploads"
          Resource:
            - "arn:aws:s3:::cmiml-feature-media"
            - "arn:aws:s3:::cmiml-feature-answer",
            - "arn:aws:s3:::cmiml-feature-operations"

        - Sid: S3WriteEtc
          Effect: Allow
          Action:
            - "s3:PutObject*"
            - "s3:GetObject*"
            - "s3:DeleteObject"
            - "s3:ListBucketMultipartUploads"
          Resource:
            - "arn:aws:s3:::cmiml-feature-media/*",
            - "arn:aws:s3:::cmiml-dev-answer/*",
            - "arn:aws:s3:::cmiml-dev-operations/*"



Outputs:
  # 1. You need to output the IAM ManagedPolicy so that Copilot can add it as a managed policy to your ECS task role.
  MyTableAccessPolicyArn:
    Description: "The ARN of the ManagedPolicy to attach to the task role."
    Value: !Ref MyTableAccessPolicy