version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "pipenv"
    commit-message:
      prefix: "[pip] Dependabot:"
      prefix-development: "[pip-dev] Dependabot:"
    pull-request-branch-name:
      separator: "-"
