fail_fast: true

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --check .
        language: system
        types: [python]
        pass_filenames: false

      - id: isort
        name: isort
        entry: isort --check-only .
        language: system
        types: [python]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 .
        language: system
        types: [python]
        pass_filenames: false
        additional_dependencies: ["flake8-fastapi==0.7.0"]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        exclude: "apps/girderformindlogger|apps/migrate"

      - id: git-secrets
        name: git-secrets
        entry: git secrets --scan
        language: system
