fail_fast: true

repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check .
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff-format
        name: ruff-format
        entry: ruff format --check .
        language: system
        types: [python]
        pass_filenames: false

      - id: isort
        name: isort
        entry: isort --check-only .
        language: system
        types: [python]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        exclude: "apps/jsonld_converter"

      - id: git-secrets
        name: git-secrets
        entry: git secrets --scan
        language: system
