version: "3"

services:

  postgres:
    image: postgres:14
    container_name: mindlogger_postgres
    environment:
      POSTGRES_HOST: ${DATABASE__HOST}
      POSTGRES_PORT: ${DATABASE__PORT}
      POSTGRES_PASSWORD: ${DATABASE__PASSWORD}
      POSTGRES_USER: ${DATABASE__USER}
      POSTGRES_DB: ${DATABASE__DB}
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mindlogger_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis
    ports:
      - 6379:6379

  app:
    stdin_open: true
    tty: true
    image: mindlogger_webapp
    build:
      context: .
      dockerfile: ./compose/fastapi/Dockerfile
    container_name: mindlogger_app
    entrypoint: /fastapi-entrypoint
    command: /fastapi-start
    env_file: .env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - 8000:80
    volumes:
      - ./:/app/

  report-consumer:
    stdin_open: true
    tty: true
    image: mindlogger_consumer
    build:
      context: .
      dockerfile: ./compose/fastapi/Dockerfile
    container_name: mindlogger_consumer
    entrypoint: /fastapi-entrypoint
    command: /fastapi-consume-report
    env_file: .env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - ./:/app/

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mindlogger_mailhog
    ports:
      - 8025:8025
      - 1025:1025
  
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: mindlogger_mongo
    volumes:
      - db_data:/data/db
    
    

volumes:
  pg_data: {}
  db_data: {}
  