services:

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: mindlogger_postgres
    container_name: mindlogger_postgres
    environment:
      POSTGRES_HOST: ${DATABASE__HOST}
      POSTGRES_PORT: ${DATABASE__PORT}
      POSTGRES_PASSWORD: ${DATABASE__PASSWORD}
      POSTGRES_USER: ${DATABASE__USER}
      POSTGRES_DB: ${DATABASE__DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  postgres-arb:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: mindlogger_postgres_arb
    container_name: mindlogger_postgres_arb
    environment:
      POSTGRES_HOST: ${DATABASE__HOST}
      POSTGRES_PORT: 65432
      POSTGRES_PASSWORD: ${DATABASE__PASSWORD}
      POSTGRES_USER: ${DATABASE__USER}
      POSTGRES_DB: ${DATABASE__DB}
    ports:
      - "65432:65432"
    volumes:
      - pg_arb_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mindlogger_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    container_name: mindlogger_redis
    ports:
      - "6379:6379"

  app:
    stdin_open: true
    tty: true
    image: mindlogger_backend
    container_name: mindlogger_backend
    build:
      context: .
      dockerfile: ./compose/fastapi/Dockerfile
    entrypoint: /fastapi-entrypoint
    command: /start-backend-datadog
    env_file: .env
    environment:
      DATABASE__HOST: postgres
      REDIS__HOST: redis
      MAILING__MAIL__SERVER: mailhog
      RABBITMQ__URL: rabbitmq
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - mailhog
    ports:
      - "8000:80"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml


  worker:
    build:
      context: .
      dockerfile: ./compose/fastapi/Dockerfile
    image: mindlogger_worker
    container_name: mindlogger_worker
    entrypoint: /fastapi-entrypoint
    command: ['/start-worker']
    env_file: .env
    environment:
      DATABASE__HOST: postgres
      REDIS__HOST: redis
      MAILING__MAIL__SERVER: mailhog
      RABBITMQ__URL: rabbitmq
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - mailhog

  scheduler:
    build:
      context: .
      dockerfile: ./compose/fastapi/Dockerfile
    image: mindlogger_scheduler
    container_name: mindlogger_scheduler
    entrypoint: /fastapi-entrypoint
    command: ['/start-scheduler']
    env_file: .env
    environment:
      DATABASE__HOST: postgres
      REDIS__HOST: redis
      MAILING__MAIL__SERVER: mailhog
      RABBITMQ__URL: rabbitmq
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml
    depends_on:
      - postgres
      - redis
      - rabbitmq

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mindlogger_mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  minio:
    image: minio/minio
    container_name: mindlogger_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioaccess
      MINIO_ROOT_PASSWORD: miniosecret
    volumes:
      - datastore:/data
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    container_name: mindlogger_minio_mc
    environment:
      CDN__BUCKET: "${CDN__BUCKET:-cmi-media-local}"
      CDN__BUCKET_ANSWER: "${CDN__BUCKET_ANSWER:-cmi-answer-local}"
      CDN__BUCKET_OPERATIONS: "${CDN__BUCKET_OPERATIONS:-cmi-ops-local}"
      CDN__BUCKET_OVERRIDE: "${CDN__BUCKET_OVERRIDE:-cmi-media-local-dr}"
      CDN__BUCKET_ANSWER_OVERRIDE: "${CDN__BUCKET_ANSWER_OVERRIDE:-cmi-answer-local-dr}"
      CDN__BUCKET_OPERATIONS_OVERRIDE: "${CDN__BUCKET_OPERATIONS_OVERRIDE:-cmi-ops-local-dr}"
    depends_on:
      - minio
    volumes:
      - './compose/minio:/etc/minio'
    entrypoint: /etc/minio/create_bucket.sh

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node
    environment:
      discovery.type: single-node
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH__PASSWORD}
      node.name: opensearch
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
      explore.enabled: true
    ports:
      - "5601:5601"
    networks:
      - opensearch-net

networks:
  opensearch-net:

volumes:
  pg_data: {}
  pg_arb_data: {}
  datastore: {}
  opensearch-data: {}
