version: "3"

services:

  postgres:
    image: postgres:14
    container_name: mindlogger_postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379

  web_app:
    image: mindlogger_backend
    build:
      context: .
      dockerfile: ./compose/fastapi/Dockerfile
    container_name: mindlogger_backend_web_app
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:80
    volumes:
      - ./:/app/

volumes:
  pg_data: {}
