version: "3"

services:

  postgres:
    image: postgres:14
    container_name: postgres
    env_file: .env
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.4
    ports:
      - 6379:6379
  fastapi:
    image: fastapi_service
    container_name: fastapi_service
    build:
      context: .
      dockerfile: ./compose/fastapi/Dockerfile
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - 8012:80
    volumes:
      - ./:/app/

volumes:
  pg_data: {}
