"""Applets and Permissions

Revision ID: 23391735c89d
Revises: ba9e58c6b7ef
Create Date: 2022-12-05 09:45:07.131334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23391735c89d"
down_revision = "ba9e58c6b7ef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("displayName", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("displayName"),
    )
    op.create_table(
        "user_applet_accesses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("applet_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN",
                "CONTENT_MANAGER",
                "DATA_MANAGER",
                "CASE_MANAGER",
                "RESPONDENTS_MANAGER",
                "REVIEWERS_MANAGER",
                "MANAGERS_MANAGER",
                "REVIEWER",
                "RESPONDENT",
                name="role",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["applet_id"],
            ["applets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id", "user_id", "applet_id", "role"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_applet_accesses")
    op.drop_table("applets")
    # ### end Alembic commands ###
