"""themes schema fix naming

Revision ID: a18f0e4bd4e9
Revises: 112f3082051f
Create Date: 2022-12-26 18:28:44.064140

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a18f0e4bd4e9"
down_revision = "112f3082051f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "themes",
        sa.Column("background_image", sa.String(length=100), nullable=True),
    )
    op.drop_column("themes", "backgroun_image")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "themes",
        sa.Column(
            "backgroun_image",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("themes", "background_image")
    # ### end Alembic commands ###
