"""Setup activities

Revision ID: b195b72b002f
Revises: 3fbc8940a60d
Create Date: 2022-12-12 22:23:54.471401

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b195b72b002f"
down_revision = "3fbc8940a60d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("applet_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("splash_screen", sa.Text(), nullable=True),
        sa.Column("image", sa.Text(), nullable=True),
        sa.Column("show_all_at_once", sa.Boolean(), nullable=True),
        sa.Column("is_skippable", sa.Boolean(), nullable=True),
        sa.Column("is_reviewable", sa.Boolean(), nullable=True),
        sa.Column("response_is_editable", sa.Boolean(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["applet_id"], ["applets.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activity_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("response_type", sa.Text(), nullable=True),
        sa.Column("answers", sa.JSON(), nullable=True),
        sa.Column("color_palette", sa.Text(), nullable=True),
        sa.Column("timer", sa.Integer(), nullable=True),
        sa.Column("has_token_value", sa.Boolean(), nullable=True),
        sa.Column("is_skippable", sa.Boolean(), nullable=True),
        sa.Column("has_alert", sa.Boolean(), nullable=True),
        sa.Column("has_score", sa.Boolean(), nullable=True),
        sa.Column("is_random", sa.Boolean(), nullable=True),
        sa.Column("is_able_to_move_to_previous", sa.Boolean(), nullable=True),
        sa.Column("has_text_response", sa.Boolean(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"], ["activities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity_items")
    op.drop_table("activities")
    # ### end Alembic commands ###
