"""notification log schema

Revision ID: 79ecca6511a0
Revises: b195b72b002f
Create Date: 2022-12-29 13:23:28.039194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "79ecca6511a0"
down_revision = "b195b72b002f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("device_id", sa.String(), nullable=True),
        sa.Column("action_type", sa.String(), nullable=True),
        sa.Column("notification_descriptions", sa.String(), nullable=True),
        sa.Column("notification_in_queue", sa.String(), nullable=True),
        sa.Column("scheduled_notifications", sa.String(), nullable=True),
        sa.Column(
            "notification_descriptions_updated", sa.Boolean(), nullable=True
        ),
        sa.Column(
            "notifications_in_queue_updated", sa.Boolean(), nullable=True
        ),
        sa.Column(
            "scheduled_notifications_updated", sa.Boolean(), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_logs")
    # ### end Alembic commands ###
