"""add encryption, remove password

Revision ID: 2d9cbd7b0928
Revises: 64b61a1e037c
Create Date: 2023-05-11 06:02:55.037711

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2d9cbd7b0928"
down_revision = "e3c136d62018"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applets",
        sa.Column(
            "encryption",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.drop_column("applets", "system_encrypted_key")
    op.drop_column("applets", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applets",
        sa.Column(
            "hashed_password", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "applets",
        sa.Column(
            "system_encrypted_key",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("applets", "encryption")
    op.execute("""delete from answers;""")
    # ### end Alembic commands ###
