"""add is_published to applet

Revision ID: 54b497530baf
Revises: 2d9cbd7b0928
Create Date: 2023-05-17 05:40:41.245639

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "54b497530baf"
down_revision = "2d9cbd7b0928"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applets", sa.Column("is_published", sa.Boolean(), nullable=True)
    )
    op.execute("""
        update applets set is_published = true;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applets", "is_published")
    # ### end Alembic commands ###
