"""add applet activity answer

Revision ID: d0fab61b4d4e
Revises: eb01de0a06f8
Create Date: 2023-01-31 09:11:17.217808

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d0fab61b4d4e"
down_revision = "eb01de0a06f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answers_activity_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("respondent_id", sa.Integer(), nullable=False),
        sa.Column(
            "answer", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("applet_id", sa.Integer(), nullable=False),
        sa.Column("applet_history_id_version", sa.String(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column(
            "activity_item_history_id_version", sa.String(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"], ["activities.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["activity_item_history_id_version"],
            ["activity_item_histories.id_version"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["applet_history_id_version"],
            ["applet_histories.id_version"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["applet_id"], ["applets.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["respondent_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "answers_flow_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("respondent_id", sa.Integer(), nullable=False),
        sa.Column(
            "answer", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("applet_id", sa.Integer(), nullable=False),
        sa.Column("applet_history_id_version", sa.String(), nullable=False),
        sa.Column("flow_item_history_id_version", sa.String(), nullable=False),
        sa.Column(
            "activity_item_history_id_version", sa.String(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["activity_item_history_id_version"],
            ["activity_item_histories.id_version"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["applet_history_id_version"],
            ["applet_histories.id_version"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["applet_id"], ["applets.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["flow_item_history_id_version"],
            ["flow_item_histories.id_version"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["respondent_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("answers_flow_items")
    op.drop_table("answers_activity_items")
    # ### end Alembic commands ###
