"""Add report_included_item to activity and flow

Revision ID: 8f38f890e348
Revises: 947d6b1da437
Create Date: 2023-08-02 19:11:28.079703

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8f38f890e348"
down_revision = "947d6b1da437"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities",
        sa.Column("report_included_item_name", sa.Text(), nullable=True),
    )
    op.add_column(
        "activity_histories",
        sa.Column("report_included_item_name", sa.Text(), nullable=True),
    )
    op.add_column(
        "flow_histories",
        sa.Column("report_included_activity_name", sa.Text(), nullable=True),
    )
    op.add_column(
        "flow_histories",
        sa.Column("report_included_item_name", sa.Text(), nullable=True),
    )
    op.add_column(
        "flows",
        sa.Column("report_included_activity_name", sa.Text(), nullable=True),
    )
    op.add_column(
        "flows",
        sa.Column("report_included_item_name", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flows", "report_included_item_name")
    op.drop_column("flows", "report_included_activity_name")
    op.drop_column("flow_histories", "report_included_item_name")
    op.drop_column("flow_histories", "report_included_activity_name")
    op.drop_column("activity_histories", "report_included_item_name")
    op.drop_column("activities", "report_included_item_name")
    # ### end Alembic commands ###
