"""Add extra_fields to history tables

Revision ID: f41d934e88f9
Revises: 8f38f890e348
Create Date: 2023-08-03 12:39:49.039493

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f41d934e88f9"
down_revision = "8f38f890e348"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity_histories",
        sa.Column(
            "extra_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
    )
    op.add_column(
        "activity_item_histories",
        sa.Column(
            "extra_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
    )
    op.add_column(
        "applet_histories",
        sa.Column(
            "extra_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
    )
    op.add_column(
        "flow_histories",
        sa.Column(
            "extra_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flow_histories", "extra_fields")
    op.drop_column("applet_histories", "extra_fields")
    op.drop_column("activity_item_histories", "extra_fields")
    op.drop_column("activity_histories", "extra_fields")
    # ### end Alembic commands ###
