"""Add performance_task_type to the table

Revision ID: 186481f0c0cc
Revises: 63a2a290c7e6
Create Date: 2023-12-06 13:47:49.694746

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "186481f0c0cc"
down_revision = "63a2a290c7e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities",
        sa.Column(
            "performance_task_type", sa.String(length=255), nullable=True
        ),
    )
    op.add_column(
        "activity_histories",
        sa.Column(
            "performance_task_type", sa.String(length=255), nullable=True
        ),
    )
    conn = op.get_bind()
    conn.execute(
        sa.text(
            """
                with
                performance as (
                    select distinct
                        activity_id,
                        case when response_type in ('ABTrails', 'flanker') then response_type
                            else config->>'user_input_type'
                        end as performance_task_type
                    from activity_items
                    where response_type in ('ABTrails', 'flanker')
                        or response_type = 'stabilityTracker' and config->>'user_input_type' in ('touch', 'gyroscope')
                )
                update activities set performance_task_type = performance.performance_task_type
                from performance
                where id = performance.activity_id
            """
        )
    )
    conn.execute(
        sa.text(
            """
                with
                performance as (
                    select distinct
                        activity_id,
                        case when response_type in ('ABTrails', 'flanker') then response_type
                            else config->>'user_input_type'
                        end as performance_task_type
                    from activity_item_histories
                    where response_type in ('ABTrails', 'flanker')
                        or response_type = 'stabilityTracker' and config->>'user_input_type' in ('touch', 'gyroscope')
                )
                update activity_histories set performance_task_type = performance.performance_task_type
                from performance
                where id_version = performance.activity_id
            """
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity_histories", "performance_task_type")
    op.drop_column("activities", "performance_task_type")
    # ### end Alembic commands ###
