"""migration email

Revision ID: 6e20542f7c86
Revises: f41d934e88f9
Create Date: 2023-08-08 15:35:42.410142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e20542f7c86"
down_revision = "f41d934e88f9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "activities",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "activity_events",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "activity_events",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "activity_histories",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "activity_histories",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "activity_item_histories",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "activity_item_histories",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "activity_items",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "activity_items",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "alerts", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "alerts", sa.Column("migrated_updated", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "answer_notes",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "answer_notes",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "answers", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "answers", sa.Column("migrated_updated", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "answers_items",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "answers_items",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "applet_histories",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "applet_histories",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "applets", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "applets", sa.Column("migrated_updated", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "cart", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "cart", sa.Column("migrated_updated", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "events", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "events", sa.Column("migrated_updated", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "flow_events", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "flow_events",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "flow_histories",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "flow_histories",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "flow_item_histories",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "flow_item_histories",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "flow_items", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "flow_items",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "flows", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "flows", sa.Column("migrated_updated", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "folder_applets",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "folder_applets",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "folders", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "folders", sa.Column("migrated_updated", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "invitations", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "invitations",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "library", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "library", sa.Column("migrated_updated", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "notification_logs",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "notification_logs",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "notifications",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "notifications",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "periodicity", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "periodicity",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "reminders", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "reminders",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "reusable_item_choices",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "reusable_item_choices",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "themes", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "themes", sa.Column("migrated_updated", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "transfer_ownership",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "transfer_ownership",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "user_applet_accesses",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "user_applet_accesses",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "user_devices",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "user_devices",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "user_events", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "user_events",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "user_pins", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "user_pins",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "users", sa.Column("migrated_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("migrated_updated", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "email_aes_encrypted", sa.LargeBinary(length=100), nullable=True
        ),
    )
    op.add_column(
        "users_workspaces",
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "users_workspaces",
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_workspaces", "migrated_updated")
    op.drop_column("users_workspaces", "migrated_date")
    op.drop_column("users", "email_aes_encrypted")
    op.drop_column("users", "migrated_updated")
    op.drop_column("users", "migrated_date")
    op.drop_column("user_pins", "migrated_updated")
    op.drop_column("user_pins", "migrated_date")
    op.drop_column("user_events", "migrated_updated")
    op.drop_column("user_events", "migrated_date")
    op.drop_column("user_devices", "migrated_updated")
    op.drop_column("user_devices", "migrated_date")
    op.drop_column("user_applet_accesses", "migrated_updated")
    op.drop_column("user_applet_accesses", "migrated_date")
    op.drop_column("transfer_ownership", "migrated_updated")
    op.drop_column("transfer_ownership", "migrated_date")
    op.drop_column("themes", "migrated_updated")
    op.drop_column("themes", "migrated_date")
    op.drop_column("reusable_item_choices", "migrated_updated")
    op.drop_column("reusable_item_choices", "migrated_date")
    op.drop_column("reminders", "migrated_updated")
    op.drop_column("reminders", "migrated_date")
    op.drop_column("periodicity", "migrated_updated")
    op.drop_column("periodicity", "migrated_date")
    op.drop_column("notifications", "migrated_updated")
    op.drop_column("notifications", "migrated_date")
    op.drop_column("notification_logs", "migrated_updated")
    op.drop_column("notification_logs", "migrated_date")
    op.drop_column("library", "migrated_updated")
    op.drop_column("library", "migrated_date")
    op.drop_column("invitations", "migrated_updated")
    op.drop_column("invitations", "migrated_date")
    op.drop_column("folders", "migrated_updated")
    op.drop_column("folders", "migrated_date")
    op.drop_column("folder_applets", "migrated_updated")
    op.drop_column("folder_applets", "migrated_date")
    op.drop_column("flows", "migrated_updated")
    op.drop_column("flows", "migrated_date")
    op.drop_column("flow_items", "migrated_updated")
    op.drop_column("flow_items", "migrated_date")
    op.drop_column("flow_item_histories", "migrated_updated")
    op.drop_column("flow_item_histories", "migrated_date")
    op.drop_column("flow_histories", "migrated_updated")
    op.drop_column("flow_histories", "migrated_date")
    op.drop_column("flow_events", "migrated_updated")
    op.drop_column("flow_events", "migrated_date")
    op.drop_column("events", "migrated_updated")
    op.drop_column("events", "migrated_date")
    op.drop_column("cart", "migrated_updated")
    op.drop_column("cart", "migrated_date")
    op.drop_column("applets", "migrated_updated")
    op.drop_column("applets", "migrated_date")
    op.drop_column("applet_histories", "migrated_updated")
    op.drop_column("applet_histories", "migrated_date")
    op.drop_column("answers_items", "migrated_updated")
    op.drop_column("answers_items", "migrated_date")
    op.drop_column("answers", "migrated_updated")
    op.drop_column("answers", "migrated_date")
    op.drop_column("answer_notes", "migrated_updated")
    op.drop_column("answer_notes", "migrated_date")
    op.drop_column("alerts", "migrated_updated")
    op.drop_column("alerts", "migrated_date")
    op.drop_column("activity_items", "migrated_updated")
    op.drop_column("activity_items", "migrated_date")
    op.drop_column("activity_item_histories", "migrated_updated")
    op.drop_column("activity_item_histories", "migrated_date")
    op.drop_column("activity_histories", "migrated_updated")
    op.drop_column("activity_histories", "migrated_date")
    op.drop_column("activity_events", "migrated_updated")
    op.drop_column("activity_events", "migrated_date")
    op.drop_column("activities", "migrated_updated")
    op.drop_column("activities", "migrated_date")
    # ### end Alembic commands ###
