"""Add extra fields to Applet, Activity, ActivityItem, ActivityFlow

Revision ID: 1e64f22ed834
Revises: 595414bdf04f
Create Date: 2023-04-13 20:54:16.683101

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1e64f22ed834"
down_revision = "595414bdf04f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities",
        sa.Column(
            "extra_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
    )
    op.add_column(
        "activity_items",
        sa.Column(
            "extra_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
    )
    op.add_column(
        "applets",
        sa.Column(
            "extra_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
    )
    op.add_column(
        "flows",
        sa.Column(
            "extra_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flows", "extra_fields")
    op.drop_column("applets", "extra_fields")
    op.drop_column("activity_items", "extra_fields")
    op.drop_column("activities", "extra_fields")
    # ### end Alembic commands ###
