"""add conditional_logic into activity_item

Revision ID: e3c136d62018
Revises: 64b61a1e037c
Create Date: 2023-05-06 08:45:13.287587

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e3c136d62018"
down_revision = "64b61a1e037c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity_item_histories",
        sa.Column(
            "conditional_logic",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "activity_items",
        sa.Column(
            "conditional_logic",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity_items", "conditional_logic")
    op.drop_column("activity_item_histories", "conditional_logic")
    # ### end Alembic commands ###
