"""add history

Revision ID: 6b5d7651b94f
Revises: 701da205e3b7
Create Date: 2023-01-12 12:44:12.113784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6b5d7651b94f"
down_revision = "701da205e3b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applet_histories",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column(
            "description",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "about", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("image", sa.String(length=255), nullable=True),
        sa.Column("watermark", sa.String(length=255), nullable=True),
        sa.Column("theme_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.String(length=255), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("report_server_ip", sa.Text(), nullable=True),
        sa.Column("report_public_key", sa.Text(), nullable=True),
        sa.Column(
            "report_recipients",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("report_include_user_id", sa.Boolean(), nullable=True),
        sa.Column("report_include_case_id", sa.Boolean(), nullable=True),
        sa.Column("report_email_body", sa.Text(), nullable=True),
        sa.Column("id_version", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id_version"),
    )
    op.create_table(
        "activity_histories",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("guid", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column(
            "description",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("splash_screen", sa.Text(), nullable=True),
        sa.Column("image", sa.Text(), nullable=True),
        sa.Column("show_all_at_once", sa.Boolean(), nullable=True),
        sa.Column("is_skippable", sa.Boolean(), nullable=True),
        sa.Column("is_reviewable", sa.Boolean(), nullable=True),
        sa.Column("response_is_editable", sa.Boolean(), nullable=True),
        sa.Column("ordering", sa.REAL(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("id_version", sa.String(), nullable=False),
        sa.Column("applet_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["applet_id"], ["applet_histories.id_version"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id_version"),
    )
    op.create_table(
        "flow_histories",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("guid", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "description",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("is_single_report", sa.Boolean(), nullable=True),
        sa.Column("hide_badge", sa.Boolean(), nullable=True),
        sa.Column("ordering", sa.REAL(), nullable=True),
        sa.Column("id_version", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("applet_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["applet_id"], ["applet_histories.id_version"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id_version"),
    )
    op.create_table(
        "activity_item_histories",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column(
            "question", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("response_type", sa.Text(), nullable=True),
        sa.Column(
            "answers", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("color_palette", sa.Text(), nullable=True),
        sa.Column("timer", sa.Integer(), nullable=True),
        sa.Column("has_token_value", sa.Boolean(), nullable=True),
        sa.Column("is_skippable", sa.Boolean(), nullable=True),
        sa.Column("has_alert", sa.Boolean(), nullable=True),
        sa.Column("has_score", sa.Boolean(), nullable=True),
        sa.Column("is_random", sa.Boolean(), nullable=True),
        sa.Column("is_able_to_move_to_previous", sa.Boolean(), nullable=True),
        sa.Column("has_text_response", sa.Boolean(), nullable=True),
        sa.Column("ordering", sa.REAL(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("id_version", sa.String(), nullable=False),
        sa.Column("activity_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity_histories.id_version"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_version"),
    )
    op.create_table(
        "flow_item_histories",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("ordering", sa.REAL(), nullable=True),
        sa.Column("id_version", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("activity_flow_id", sa.String(), nullable=True),
        sa.Column("activity_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_flow_id"],
            ["flow_histories.id_version"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id_version"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flow_item_histories")
    op.drop_table("activity_item_histories")
    op.drop_table("flow_histories")
    op.drop_table("activity_histories")
    op.drop_table("applet_histories")
    # ### end Alembic commands ###
