"""add is_edited to assessment answer

Revision ID: ee42eec076eb
Revises: 70feaadd3564
Create Date: 2023-05-31 14:34:42.471460

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ee42eec076eb"
down_revision = "70feaadd3564"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assessment_answer_items",
        sa.Column("is_edited", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assessment_answer_items", "is_edited")
    # ### end Alembic commands ###
