"""add fields alert_message specific_answer to alerts

Revision ID: 702699f11a47
Revises: ffb241cb1926
Create Date: 2023-03-27 23:23:38.151617

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "702699f11a47"
down_revision = "ffb241cb1926"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alerts", sa.Column("alert_message", sa.String(), nullable=False)
    )
    op.add_column(
        "alerts", sa.Column("specific_answer", sa.Text(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alerts", "specific_answer")
    op.drop_column("alerts", "alert_message")
    # ### end Alembic commands ###
