"""Add unique constraint applet user role

Revision ID: a6c3c3398779
Revises: 94558f04015a
Create Date: 2023-08-21 16:29:23.196497

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a6c3c3398779"
down_revision = "94558f04015a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "unique_user_applet_role",
        "user_applet_accesses",
        ["user_id", "applet_id", "role"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("unique_user_applet_role", table_name="user_applet_accesses")
    # ### end Alembic commands ###
