"""reusable activity item choices

Revision ID: ea571b4b36c0
Revises: f98e76b4a5f2
Create Date: 2023-01-03 08:58:41.943265

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea571b4b36c0"
down_revision = "f98e76b4a5f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reusable_item_choices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_name", sa.String(length=100), nullable=False),
        sa.Column("token_value", sa.Integer(), nullable=False),
        sa.Column("input_type", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "token_name",
            "token_value",
            "input_type",
            name="_unique_item_choices",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reusable_item_choices")
    # ### end Alembic commands ###
