"""change answer type

Revision ID: fa1f97713a5c
Revises: 113a350cf8cd
Create Date: 2023-03-16 16:08:55.661362

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fa1f97713a5c"
down_revision = "113a350cf8cd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "answers_activity_items", sa.Column("answer", sa.Text(), nullable=True)
    )
    op.add_column(
        "answers_flow_items", sa.Column("answer", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answers_flow_items", "answer")
    op.drop_column("answers_activity_items", "answer")
    # ### end Alembic commands ###
