"""Add unique constraint applet user role

Revision ID: 6bdd8ee7cbe6
Revises: 071cca4a1aa4
Create Date: 2023-08-17 12:06:23.425315

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6bdd8ee7cbe6"
down_revision = "071cca4a1aa4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "unique_user_applet_role",
        "user_applet_accesses",
        ["user_id", "applet_id", "role"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("unique_user_applet_role", table_name="user_applet_accesses")
    # ### end Alembic commands ###
