"""add is default attribute to theme

Revision ID: a8f5e4ea81bb
Revises: 8469536f11b3
Create Date: 2023-09-26 16:19:46.253502

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a8f5e4ea81bb"
down_revision = "8469536f11b3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "themes",
        sa.Column(
            "is_default",
            sa.Boolean(),
            nullable=False,
            server_default="false"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("themes", "is_default")
    # ### end Alembic commands ###
