"""added is_legacy_deleted_respondent

Revision ID: c60599479c20
Revises: a4b4299c90c5
Create Date: 2023-09-07 12:59:53.983395

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c60599479c20"
down_revision = "39d0778295f1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_legacy_deleted_respondent",
            sa.Boolean(),
            server_default="false",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_legacy_deleted_respondent")
    # ### end Alembic commands ###
