"""folder_id ondelete cascade

Revision ID: 79ae42ccb0d1
Revises: 34b60d19140d
Create Date: 2023-09-12 18:46:13.549948

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "79ae42ccb0d1"
down_revision = "34b60d19140d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_folder_applets_folder_id_folders",
        "folder_applets",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_folder_applets_folder_id_folders"),
        "folder_applets",
        "folders",
        ["folder_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_folder_applets_folder_id_folders"),
        "folder_applets",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_folder_applets_folder_id_folders",
        "folder_applets",
        "folders",
        ["folder_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###
