"""access link field to applet

Revision ID: ccd432ca974f
Revises: 7c258f83b437
Create Date: 2023-02-15 13:12:23.554667

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ccd432ca974f"
down_revision = "7c258f83b437"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applets",
        sa.Column("link", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.add_column(
        "applets", sa.Column("require_login", sa.Boolean(), nullable=True)
    )
    op.create_unique_constraint(op.f("uq_applets_link"), "applets", ["link"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_applets_link"), "applets", type_="unique")
    op.drop_column("applets", "require_login")
    op.drop_column("applets", "link")
    # ### end Alembic commands ###
