"""added migrated_data field to answer_item

Revision ID: a4b4299c90c5
Revises: 55508b7bf7cb
Create Date: 2023-08-25 13:48:29.864615

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a4b4299c90c5"
down_revision = "55508b7bf7cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "answers_items",
        sa.Column(
            "migrated_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answers_items", "migrated_data")
    # ### end Alembic commands ###
