"""add applet history

Revision ID: eb01de0a06f8
Revises: 98bd718c656c
Create Date: 2023-01-19 18:01:13.695584

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "eb01de0a06f8"
down_revision = "98bd718c656c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applet_histories",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column(
            "description",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "about", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("image", sa.String(length=255), nullable=True),
        sa.Column("watermark", sa.String(length=255), nullable=True),
        sa.Column("theme_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.String(length=255), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("report_server_ip", sa.Text(), nullable=True),
        sa.Column("report_public_key", sa.Text(), nullable=True),
        sa.Column(
            "report_recipients",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("report_include_user_id", sa.Boolean(), nullable=True),
        sa.Column("report_include_case_id", sa.Boolean(), nullable=True),
        sa.Column("report_email_body", sa.Text(), nullable=True),
        sa.Column("id_version", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id_version"),
    )
    op.create_table(
        "activity_histories",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("guid", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column(
            "description",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("splash_screen", sa.Text(), nullable=True),
        sa.Column("image", sa.Text(), nullable=True),
        sa.Column("show_all_at_once", sa.Boolean(), nullable=True),
        sa.Column("is_skippable", sa.Boolean(), nullable=True),
        sa.Column("is_reviewable", sa.Boolean(), nullable=True),
        sa.Column("response_is_editable", sa.Boolean(), nullable=True),
        sa.Column("ordering", sa.REAL(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("id_version", sa.String(), nullable=False),
        sa.Column("applet_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["applet_id"], ["applet_histories.id_version"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id_version"),
    )
    op.create_table(
        "flow_histories",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("guid", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "description",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("is_single_report", sa.Boolean(), nullable=True),
        sa.Column("hide_badge", sa.Boolean(), nullable=True),
        sa.Column("ordering", sa.REAL(), nullable=True),
        sa.Column("id_version", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("applet_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["applet_id"], ["applet_histories.id_version"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id_version"),
    )
    op.create_table(
        "activity_item_histories",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column(
            "question", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("response_type", sa.Text(), nullable=True),
        sa.Column(
            "answers", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("color_palette", sa.Text(), nullable=True),
        sa.Column("timer", sa.Integer(), nullable=True),
        sa.Column("has_token_value", sa.Boolean(), nullable=True),
        sa.Column("is_skippable", sa.Boolean(), nullable=True),
        sa.Column("has_alert", sa.Boolean(), nullable=True),
        sa.Column("has_score", sa.Boolean(), nullable=True),
        sa.Column("is_random", sa.Boolean(), nullable=True),
        sa.Column("is_able_to_move_to_previous", sa.Boolean(), nullable=True),
        sa.Column("has_text_response", sa.Boolean(), nullable=True),
        sa.Column("ordering", sa.REAL(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("id_version", sa.String(), nullable=False),
        sa.Column("activity_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity_histories.id_version"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_version"),
    )
    op.create_table(
        "flow_item_histories",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("ordering", sa.REAL(), nullable=True),
        sa.Column("id_version", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("activity_flow_id", sa.String(), nullable=True),
        sa.Column("activity_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_flow_id"],
            ["flow_histories.id_version"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity_histories.id_version"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id_version"),
    )
    op.alter_column(
        "applets", "creator_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.create_foreign_key(
        "applet_creator_id",
        "applets",
        "users",
        ["creator_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "flow_activity_id",
        "flow_items",
        "activities",
        ["activity_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("flow_activity_id", "flow_items", type_="foreignkey")
    op.drop_constraint("applet_creator_id", "applets", type_="foreignkey")
    op.alter_column(
        "applets", "creator_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_table("flow_item_histories")
    op.drop_table("activity_item_histories")
    op.drop_table("flow_histories")
    op.drop_table("activity_histories")
    op.drop_table("applet_histories")
    # ### end Alembic commands ###
