"""remove users fields first_name last_name

Revision ID: 06b4cf872167
Revises: 879e5b56ca8b
Create Date: 2023-08-23 12:48:37.295896

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "06b4cf872167"
down_revision = "879e5b56ca8b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "first_name",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "last_name",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
