"""add theme uniqueness

Revision ID: cc82617b883f
Revises: 735ef98e2c6e
Create Date: 2023-03-09 13:37:38.315018

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc82617b883f"
down_revision = "735ef98e2c6e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_themes_name"), "themes", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_themes_name"), "themes", type_="unique")
    # ### end Alembic commands ###
