"""Add anonymous respondent

Revision ID: 18d4bf0ea62b
Revises: 02e785b2b03b
Create Date: 2023-06-06 12:23:47.191810

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "18d4bf0ea62b"
down_revision = "02e785b2b03b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_anonymous_respondent",
            sa.Boolean(),
            server_default="false",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_anonymous_respondent")
    # ### end Alembic commands ###
