"""add score_and_section field

Revision ID: bb67d8d318aa
Revises: 2d9cbd7b0928
Create Date: 2023-05-23 09:22:37.023868

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bb67d8d318aa"
down_revision = "2d9cbd7b0928"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities",
        sa.Column(
            "scores_and_reports",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "activities",
        sa.Column(
            "subscales", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "activity_histories",
        sa.Column(
            "scores_and_reports",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "activity_histories",
        sa.Column(
            "subscales", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity_histories", "subscales")
    op.drop_column("activity_histories", "scores_and_reports")
    op.drop_column("activities", "subscales")
    op.drop_column("activities", "scores_and_reports")
    # ### end Alembic commands ###
