"""add answer group

Revision ID: 8953aa43e382
Revises: f681621bf85d
Create Date: 2023-04-11 13:06:19.960723

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8953aa43e382"
down_revision = "f681621bf85d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""truncate answers_activity_items;""")
    op.execute("""truncate answers_flow_items;""")
    op.create_table(
        "answers",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("applet_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("flow_history_id", sa.String(), nullable=True),
        sa.Column("activity_history_id", sa.String(), nullable=False),
        sa.Column(
            "respondent_id", postgresql.UUID(as_uuid=True), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["activity_history_id"],
            ["activity_histories.id_version"],
            name=op.f("fk_answers_activity_history_id_activity_histories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["flow_history_id"],
            ["flow_histories.id_version"],
            name=op.f("fk_answers_flow_history_id_flow_histories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["respondent_id"],
            ["users.id"],
            name=op.f("fk_answers_respondent_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answers")),
    )
    op.add_column(
        "answers_activity_items",
        sa.Column("answer_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_answers_activity_items_answer_id_answers"),
        "answers_activity_items",
        "answers",
        ["answer_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "answers_flow_items",
        sa.Column("answer_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_answers_flow_items_answer_id_answers"),
        "answers_flow_items",
        "answers",
        ["answer_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_answers_flow_items_answer_id_answers"),
        "answers_flow_items",
        type_="foreignkey",
    )
    op.drop_column("answers_flow_items", "answer_id")
    op.drop_constraint(
        op.f("fk_answers_activity_items_answer_id_answers"),
        "answers_activity_items",
        type_="foreignkey",
    )
    op.drop_column("answers_activity_items", "answer_id")
    op.drop_table("answers")
    # ### end Alembic commands ###
