"""add folders

Revision ID: 3fca9f91446e
Revises: 51379bc60800
Create Date: 2023-02-02 12:20:08.417400

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3fca9f91446e"
down_revision = "51379bc60800"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "applets", sa.Column("folder_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        'applet_folder', "applets", "folders", ["folder_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('applet_folder', "applets", type_="foreignkey")
    op.drop_column("applets", "folder_id")
    op.drop_table("folders")
    # ### end Alembic commands ###
