"""Creator id to applet, transfer status, email encryption

Revision ID: 7d5807b087ff
Revises: 93087521e7ee
Create Date: 2023-11-24 20:56:41.970205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7d5807b087ff"
down_revision = "93087521e7ee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applets",
        sa.Column("creator_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_applets_creator_id_users"),
        "applets",
        "users",
        ["creator_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "transfer_ownership", sa.Column("status", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transfer_ownership", "status")
    op.drop_constraint(
        op.f("fk_applets_creator_id_users"), "applets", type_="foreignkey"
    )
    op.drop_column("applets", "creator_id")
    # ### end Alembic commands ###
