"""change subscale name in activity

Revision ID: 70feaadd3564
Revises: b6601af52279
Create Date: 2023-05-30 11:33:15.667450

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "70feaadd3564"
down_revision = "b6601af52279"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities",
        sa.Column(
            "subscale_setting",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.drop_column("activities", "subscales")
    op.add_column(
        "activity_histories",
        sa.Column(
            "subscale_setting",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.drop_column("activity_histories", "subscales")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity_histories",
        sa.Column(
            "subscales",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("activity_histories", "subscale_setting")
    op.add_column(
        "activities",
        sa.Column(
            "subscales",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("activities", "subscale_setting")
    # ### end Alembic commands ###
