"""empty message

Revision ID: 651d290bd7b7
Revises: 43ea095c253a
Create Date: 2023-03-21 13:46:58.869554

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ffb241cb1926"
down_revision = "1adbcf5d00f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invitations", sa.Column("first_name", sa.String(), nullable=True)
    )
    op.add_column(
        "invitations", sa.Column("last_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invitations", "last_name")
    op.drop_column("invitations", "first_name")
    # ### end Alembic commands ###
