"""

Revision ID: ffb241cb1926
Revises: 1adbcf5d00f5
Create Date: 2023-03-23 15:03:35.117086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ffb241cb1926"
down_revision = "1adbcf5d00f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invitations", sa.Column("first_name", sa.String(), nullable=True)
    )
    op.add_column(
        "invitations", sa.Column("last_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invitations", "last_name")
    op.drop_column("invitations", "first_name")
    # ### end Alembic commands ###
