"""small themes logo

Revision ID: a7004a194160
Revises: af9a602d25ad
Create Date: 2023-09-20 18:00:25.340026

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a7004a194160"
down_revision = "af9a602d25ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("themes", sa.Column("small_logo", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("themes", "small_logo")
    # ### end Alembic commands ###
