"""add is_hidden field to activity, flow

Revision ID: 582ff2bfe42b
Revises: ffb241cb1926
Create Date: 2023-03-27 10:33:10.503486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "582ff2bfe42b"
down_revision = "ffb241cb1926"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities", sa.Column("is_hidden", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "activity_histories",
        sa.Column("is_hidden", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "flow_histories", sa.Column("is_hidden", sa.Boolean(), nullable=True)
    )
    op.add_column("flows", sa.Column("is_hidden", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flows", "is_hidden")
    op.drop_column("flow_histories", "is_hidden")
    op.drop_column("activity_histories", "is_hidden")
    op.drop_column("activities", "is_hidden")
    # ### end Alembic commands ###
