"""add last seen to user

Revision ID: 5ea08a20c2d3
Revises: 582ff2bfe42b
Create Date: 2023-03-28 12:28:07.020157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5ea08a20c2d3"
down_revision = "582ff2bfe42b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("last_seen_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_seen_at")
    # ### end Alembic commands ###
