"""Add email_aes_encrypted to user

Revision ID: f58498f5a4ad
Revises: 947d6b1da437
Create Date: 2023-08-02 12:07:56.295292

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f58498f5a4ad"
down_revision = "947d6b1da437"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email_aes_encrypted", sa.LargeBinary(length=100), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_aes_encrypted")
    # ### end Alembic commands ###
