"""add meta to invitations and user_applet_accesses

Revision ID: da1343a087ae
Revises: ef35f06a2c45
Create Date: 2023-02-23 02:39:42.720862

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "da1343a087ae"
down_revision = "ef35f06a2c45"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invitations",
        sa.Column(
            "meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "user_applet_accesses",
        sa.Column("owner_id", sa.Integer(), nullable=False),
    )
    op.add_column(
        "user_applet_accesses",
        sa.Column("invitor_id", sa.Integer(), nullable=False),
    )
    op.add_column(
        "user_applet_accesses",
        sa.Column(
            "meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("fk_user_applet_accesses_invitor_id_users"),
        "user_applet_accesses",
        "users",
        ["invitor_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_user_applet_accesses_owner_id_users"),
        "user_applet_accesses",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_applet_accesses_owner_id_users"),
        "user_applet_accesses",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_applet_accesses_invitor_id_users"),
        "user_applet_accesses",
        type_="foreignkey",
    )
    op.drop_column("user_applet_accesses", "meta")
    op.drop_column("user_applet_accesses", "invitor_id")
    op.drop_column("user_applet_accesses", "owner_id")
    op.drop_column("invitations", "meta")
    # ### end Alembic commands ###
