"""add first last name_to_user

Revision ID: ef35f06a2c45
Revises: ccd432ca974f
Create Date: 2023-02-21 20:24:49.004920

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef35f06a2c45"
down_revision = "ccd432ca974f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invitations", "title")
    op.drop_column("invitations", "body")
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=50), nullable=True)
    )
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "full_name",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.add_column(
        "invitations",
        sa.Column("body", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "invitations",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
