"""is_hidden field added into activity_item

Revision ID: 9ce2d32ab2d3
Revises: 595414bdf04f
Create Date: 2023-04-13 12:53:46.970219

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9ce2d32ab2d3"
down_revision = "595414bdf04f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity_item_histories",
        sa.Column("is_hidden", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "activity_items", sa.Column("is_hidden", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity_items", "is_hidden")
    op.drop_column("activity_item_histories", "is_hidden")
    # ### end Alembic commands ###
