"""add assessment answer

Revision ID: b6601af52279
Revises: 4cbc94279e90
Create Date: 2023-05-30 11:11:13.875648

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b6601af52279"
down_revision = "4cbc94279e90"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_answer_items",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('utc', now())"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('utc', now())"),
            nullable=True,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("answer_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("applet_history_id", sa.String(), nullable=False),
        sa.Column("activity_history_id", sa.String(), nullable=False),
        sa.Column(
            "item_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("reviewer_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("reviewer_public_key", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_history_id"],
            ["activity_histories.id_version"],
            name=op.f(
                "fk_assessment_answer_items_activity_history_id_activity_histories"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answers.id"],
            name=op.f("fk_assessment_answer_items_answer_id_answers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["applet_history_id"],
            ["applet_histories.id_version"],
            name=op.f(
                "fk_assessment_answer_items_applet_history_id_applet_histories"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_assessment_answer_items_reviewer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_answer_items")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assessment_answer_items")
    # ### end Alembic commands ###
