"""add fields to alerts

Revision ID: 9f910258cf25
Revises: 8595f5e743f4
Create Date: 2023-03-29 12:59:36.516858

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9f910258cf25"
down_revision = "8595f5e743f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alerts", sa.Column("alert_message", sa.String(), nullable=False)
    )
    op.add_column(
        "alerts", sa.Column("specific_answer", sa.Text(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alerts", "specific_answer")
    op.drop_column("alerts", "alert_message")
    # ### end Alembic commands ###
