"""Remove email from users

Revision ID: 3b59a343cd5a
Revises: f58498f5a4ad
Create Date: 2023-08-03 01:27:00.118177

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3b59a343cd5a"
down_revision = "f58498f5a4ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_email", "users", type_="unique")
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.create_unique_constraint("uq_users_email", "users", ["email"])
    # ### end Alembic commands ###
