"""Remove answer_notes.user_public_key

Revision ID: 8c59c7363c67
Revises: a8f5e4ea81bb
Create Date: 2023-09-29 17:14:32.456720

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8c59c7363c67"
down_revision = "a8f5e4ea81bb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("answer_notes", "user_public_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "answer_notes",
        sa.Column(
            "user_public_key", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
