"""Add field email_encrypted to users

Revision ID: 39d0778295f1
Revises: 6268b3e094a3
Create Date: 2023-09-06 20:43:24.330574

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "39d0778295f1"
down_revision = "6268b3e094a3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("email_encrypted", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_encrypted")
    # ### end Alembic commands ###
