"""add index

Revision ID: 89a5b28c52ea
Revises: 936c2fcb6a4c
Create Date: 2023-02-06 16:25:57.489813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "89a5b28c52ea"
down_revision = "936c2fcb6a4c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_user_applet_accesses_applet_id"),
        "user_applet_accesses",
        ["applet_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_applet_accesses_role"),
        "user_applet_accesses",
        ["role"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_applet_accesses_user_id"),
        "user_applet_accesses",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_applet_accesses_user_id"),
        table_name="user_applet_accesses",
    )
    op.drop_index(
        op.f("ix_user_applet_accesses_role"), table_name="user_applet_accesses"
    )
    op.drop_index(
        op.f("ix_user_applet_accesses_applet_id"),
        table_name="user_applet_accesses",
    )
    # ### end Alembic commands ###
