"""add is pinned to access

Revision ID: 88503a4faefc
Revises: 343916a84a24
Create Date: 2023-04-03 10:29:16.600761

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "88503a4faefc"
down_revision = "343916a84a24"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_applet_accesses",
        sa.Column("is_pinned", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_applet_accesses", "is_pinned")
    # ### end Alembic commands ###
