"""change is_assessment

Revision ID: fab41742b533
Revises: c7cc15b17084
Create Date: 2023-06-12 16:03:13.758827

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fab41742b533"
down_revision = "c7cc15b17084"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activities", "is_assessment")
    op.drop_column("activity_histories", "is_assessment")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity_histories",
        sa.Column(
            "is_assessment", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "activities",
        sa.Column(
            "is_assessment", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
