"""Add nickname encrypted field in invitation

Revision ID: 93087521e7ee
Revises: a7faad5855cc
Create Date: 2023-11-16 16:26:19.400694

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils.types.encrypted.encrypted_type import StringEncryptedType

from apps.shared.encryption import get_key

# revision identifiers, used by Alembic.
revision = "93087521e7ee"
down_revision = "a7faad5855cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invitations",
        sa.Column(
            "nickname",
            StringEncryptedType(sa.Unicode, get_key),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invitations", "nickname")
    # ### end Alembic commands ###
