"""add users fields first_name last_name

Revision ID: f5bdb061119d
Revises: 06b4cf872167
Create Date: 2023-08-23 12:49:11.979190

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f5bdb061119d"
down_revision = "06b4cf872167"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("first_name", sa.LargeBinary(length=100), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("last_name", sa.LargeBinary(length=100), nullable=True),
    )
    op.add_column(
        "invitations",
        sa.Column("first_name", sa.LargeBinary(length=100), nullable=True),
    )
    op.add_column(
        "invitations",
        sa.Column("last_name", sa.LargeBinary(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("invitations", "last_name")
    op.drop_column("invitations", "first_name")
    # ### end Alembic commands ###
