"""Library table applet id version

Revision ID: 5bfa4377709a
Revises: fab41742b533
Create Date: 2023-06-21 13:56:23.075833

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5bfa4377709a"
down_revision = "fab41742b533"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "library",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('utc', now())"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('utc', now())"),
            nullable=True,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("applet_id_version", sa.String(), nullable=False),
        sa.Column("keywords", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "search_keywords", postgresql.ARRAY(sa.String()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["applet_id_version"],
            ["applet_histories.id_version"],
            name=op.f("fk_library_applet_id_version_applet_histories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_library")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("library")
    # ### end Alembic commands ###
