"""data retention fields for applet

Revision ID: 735ef98e2c6e
Revises: e139679a5675
Create Date: 2023-03-02 07:22:21.502415

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "735ef98e2c6e"
down_revision = "e139679a5675"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applets", sa.Column("retention_period", sa.Integer(), nullable=True)
    )
    op.add_column(
        "applets",
        sa.Column("retention_type", sa.String(length=20), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applets", "retention_type")
    op.drop_column("applets", "retention_period")
    # ### end Alembic commands ###
