"""Add field nickname to user_applet_accesses

Revision ID: a7faad5855cc
Revises: 0242aa768e9d
Create Date: 2023-11-12 21:45:42.636562

"""
import json

import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils.types.encrypted.encrypted_type import StringEncryptedType

from apps.shared.encryption import get_key

# revision identifiers, used by Alembic.
revision = "a7faad5855cc"
down_revision = "0242aa768e9d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT id, meta FROM user_applet_accesses WHERE role='respondent'"
        )
    )
    op.add_column(
        "user_applet_accesses",
        sa.Column(
            "nickname",
            StringEncryptedType(sa.Unicode, get_key),
            nullable=True,
        ),
    )
    for row in result:
        pk, meta = row
        nickname = meta.get("nickname", None)
        if nickname and nickname != "":
            encrypted_field = StringEncryptedType(
                sa.Unicode, get_key
            ).process_bind_param(nickname, dialect=conn.dialect)
            meta["nickname"] = None
            conn.execute(
                sa.text(
                    f"""
                        UPDATE user_applet_accesses 
                        SET nickname = :encrypted_field, meta= :meta
                        WHERE id = :pk
                    """
                ),
                {
                    "encrypted_field": encrypted_field,
                    "meta": json.dumps(meta),
                    "pk": pk,
                },
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT id, nickname, meta FROM user_applet_accesses  WHERE role='respondent'"
        )
    )
    op.drop_column("user_applet_accesses", "nickname")
    for row in result:
        pk, nickname, meta = row
        if nickname is not None:
            decrypted_field = StringEncryptedType(
                sa.Unicode, get_key
            ).process_result_value(nickname, dialect=conn.dialect)
            meta["nickname"] = decrypted_field
            conn.execute(
                sa.text(
                    f"""
                        UPDATE user_applet_accesses
                        SET meta = :decrypted_field
                        WHERE id = :pk
                    """
                ),
                {"decrypted_field": json.dumps(meta), "pk": pk},
            )
    # ### end Alembic commands ###
