"""Remove email_hash from users

Revision ID: 0447dcc87a62
Revises: 25ea98a50fe1
Create Date: 2023-07-31 15:11:43.762881

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0447dcc87a62"
down_revision = "25ea98a50fe1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_email_hash", "users", type_="unique")
    op.drop_column("users", "email_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email_hash",
            sa.VARCHAR(length=56),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_unique_constraint("uq_users_email_hash", "users", ["email_hash"])
    # ### end Alembic commands ###
