"""add_field_pinned_at_to_applet_table

Revision ID: 2551608a53c1
Revises: da1343a087ae
Create Date: 2023-02-27 09:16:03.277138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2551608a53c1"
down_revision = "da1343a087ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applets", sa.Column("pinned_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applets", "pinned_at")
    # ### end Alembic commands ###
