"""change ondelete

Revision ID: feebb648bba7
Revises: bb7daaa5854f
Create Date: 2023-07-25 17:25:53.866289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "feebb648bba7"
down_revision = "bb7daaa5854f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_folder_applets_applet_id_applets",
        "folder_applets",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_folder_applets_applet_id_applets"),
        "folder_applets",
        "applets",
        ["applet_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_folder_applets_applet_id_applets"),
        "folder_applets",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_folder_applets_applet_id_applets",
        "folder_applets",
        "applets",
        ["applet_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###
