"""Add token_blacklist

Revision ID: 8cd84b8900cc
Revises: 879e5b56ca8b
Create Date: 2023-08-24 01:40:44.952292

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8cd84b8900cc"
down_revision = "879e5b56ca8b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_blacklist",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('utc', now())"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('utc', now())"),
            nullable=True,
        ),
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("jti", sa.Text(), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("exp", sa.DateTime(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("ACCESS", "REFRESH", name="token_purpose"),
            nullable=False,
        ),
        sa.Column("rjti", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_token_blacklist")),
    )
    op.create_index(
        op.f("ix_token_blacklist_exp"),
        "token_blacklist",
        ["exp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_token_blacklist_jti"), "token_blacklist", ["jti"], unique=True
    )
    op.create_index(
        op.f("ix_token_blacklist_rjti"),
        "token_blacklist",
        ["rjti"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_token_blacklist_rjti"), table_name="token_blacklist"
    )
    op.drop_index(op.f("ix_token_blacklist_jti"), table_name="token_blacklist")
    op.drop_index(op.f("ix_token_blacklist_exp"), table_name="token_blacklist")
    op.drop_table("token_blacklist")
    sa.Enum(name="token_purpose").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
