"""add assessment to activity

Revision ID: 4cbc94279e90
Revises: 14c4f2e988c5
Create Date: 2023-05-30 09:38:45.519078

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4cbc94279e90"
down_revision = "14c4f2e988c5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities", sa.Column("is_assessment", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "activity_histories",
        sa.Column("is_assessment", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity_histories", "is_assessment")
    op.drop_column("activities", "is_assessment")
    # ### end Alembic commands ###
