"""remove unnec column

Revision ID: 4f353d3e56f4
Revises: fa1f97713a5c
Create Date: 2023-03-17 12:33:41.235729

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4f353d3e56f4"
down_revision = "fa1f97713a5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applets", "user_encrypted_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applets",
        sa.Column(
            "user_encrypted_key", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
