"""Add new field tags to subject

Revision ID: 809b07a71159
Revises: 01115b529336
Create Date: 2024-04-01 17:46:27.821161

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "809b07a71159"
down_revision = "01115b529336"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subjects",
        sa.Column(
            "tag",
            sa.String,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subjects", "tag")
    # ### end Alembic commands ###
