"""Add subject relations meta column

Revision ID: f29263d10f57
Revises: affe09e93102
Create Date: 2024-07-08 07:23:47.432383

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f29263d10f57'
down_revision = 'affe09e93102'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_relations', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject_relations', 'meta')
    # ### end Alembic commands ###
