"""Library keywords change null to '{}'

Revision ID: f15b3f4d6e14
Revises: 01115b529336
Create Date: 2024-06-10 11:44:27.270164

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from apps.library.service import LibraryService

# revision identifiers, used by Alembic.
revision = "f15b3f4d6e14"
down_revision = "01115b529336"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "library",
        "keywords",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False,
    )
    op.alter_column(
        "library",
        "search_keywords",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "library",
        "search_keywords",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    op.alter_column(
        "library",
        "keywords",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    # ### end Alembic commands ###
