"""user activity log

Revision ID: 0bf49c6e5961
Revises: 23fe6ccfb031
Create Date: 2024-05-06 16:54:29.490317

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0bf49c6e5961"
down_revision = "62843fdc3466"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_activity_logs",
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('utc', now())"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('utc', now())"),
            nullable=True,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("firebase_token_id", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("event", sa.String(), nullable=False),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("mindlogger_content", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_activity_logs_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_activity_logs")),
    )
    op.create_index(
        op.f("ix_user_activity_logs_user_id"),
        "user_activity_logs",
        ["user_id"],
        unique=False,
    )
    op.drop_column("activities", "migrated_updated")
    op.drop_column("activity_events", "migrated_updated")
    op.drop_column("activity_histories", "migrated_updated")
    op.drop_column("activity_item_histories", "migrated_updated")
    op.drop_column("activity_items", "migrated_updated")
    op.drop_column("alerts", "migrated_updated")
    op.drop_column("answer_notes", "migrated_updated")
    op.drop_column("answers", "migrated_updated")
    op.drop_column("answers_items", "migrated_updated")
    op.drop_column("applet_histories", "migrated_updated")
    op.drop_column("applets", "migrated_updated")
    op.drop_column("cart", "migrated_updated")
    op.drop_column("cart", "migrated_date")
    op.drop_column("events", "migrated_updated")
    op.drop_column("flow_events", "migrated_updated")
    op.drop_column("flow_histories", "migrated_updated")
    op.drop_column("flow_item_histories", "migrated_updated")
    op.drop_column("flow_items", "migrated_updated")
    op.drop_column("flows", "migrated_updated")
    op.drop_column("folder_applets", "migrated_updated")
    op.drop_column("folders", "migrated_updated")
    op.drop_column("invitations", "migrated_updated")
    op.drop_column("invitations", "migrated_date")
    op.drop_column("jobs", "migrated_updated")
    op.drop_column("jobs", "migrated_date")
    op.drop_column("library", "migrated_updated")
    op.drop_column("notification_logs", "migrated_updated")
    op.drop_column("notification_logs", "migrated_date")
    op.drop_column("notifications", "migrated_updated")
    op.drop_column("periodicity", "migrated_updated")
    op.drop_column("reminders", "migrated_updated")
    op.drop_column("reusable_item_choices", "migrated_updated")
    op.drop_column("reusable_item_choices", "migrated_date")
    op.drop_column("themes", "migrated_updated")
    op.drop_column("token_blacklist", "migrated_updated")
    op.drop_column("token_blacklist", "migrated_date")
    op.drop_column("transfer_ownership", "migrated_updated")
    op.drop_column("transfer_ownership", "migrated_date")
    op.drop_column("user_applet_accesses", "migrated_updated")
    op.drop_column("user_devices", "migrated_updated")
    op.drop_column("user_devices", "migrated_date")
    op.drop_column("user_events", "migrated_updated")
    op.drop_column("user_pins", "migrated_updated")
    op.drop_column("users", "migrated_updated")
    op.drop_column("users_workspaces", "migrated_updated")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_workspaces",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user_pins",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user_events",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user_devices",
        sa.Column(
            "migrated_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user_devices",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user_applet_accesses",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "transfer_ownership",
        sa.Column(
            "migrated_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "transfer_ownership",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "token_blacklist",
        sa.Column(
            "migrated_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "token_blacklist",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "themes",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "reusable_item_choices",
        sa.Column(
            "migrated_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "reusable_item_choices",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "reminders",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "periodicity",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "notifications",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "notification_logs",
        sa.Column(
            "migrated_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "notification_logs",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "library",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "migrated_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "invitations",
        sa.Column(
            "migrated_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "invitations",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "folders",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "folder_applets",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flows",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flow_items",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flow_item_histories",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flow_histories",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flow_events",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "cart",
        sa.Column(
            "migrated_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "cart",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "applets",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "applet_histories",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "answers_items",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "answers",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "answer_notes",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "alerts",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "activity_items",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "activity_item_histories",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "activity_histories",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "activity_events",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "activities",
        sa.Column(
            "migrated_updated",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(
        op.f("ix_user_activity_logs_user_id"), table_name="user_activity_logs"
    )
    op.drop_table("user_activity_logs")
    # ### end Alembic commands ###
