"""Change integrations field type in workspaces table

Revision ID: d877f29be2f0
Revises: 70c50aba13b7
Create Date: 2024-06-17 15:46:33.965375

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d877f29be2f0"
down_revision = "70c50aba13b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users_workspaces", "integrations", type_=postgresql.JSONB(astext_type=sa.Text()),postgresql_using="array_to_json(integrations);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_workspaces", "integrations")

    op.add_column(
        "users_workspaces",
        sa.Column(
            "integrations",
            sa.ARRAY(sa.String(length=32)),
            
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
