"""remove duplicated pending invitations

Revision ID: 47405ad1f948
Revises: 3fb536a58c94
Create Date: 2024-01-05 10:23:15.939352

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "47405ad1f948"
down_revision = "3fb536a58c94"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        sa.text(
            """with
               pending as (
                    select
                        id,
                        email,
                        created_at,
                        row_number() over(
                            partition by email order by created_at desc
                        ) as num
                    from invitations
                    where status = 'pending'
                    group by id, email, created_at
               ),
               outdated as (
                    select distinct
                        id
                    from pending
                    where num != 1
               )
                delete from invitations
                using outdated
                where invitations.id = outdated.id
            """
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
