"""Add new field title to invitation

Revision ID: b94120ac22a8
Revises: a38714b9e23b
Create Date: 2024-04-16 16:58:18.611738

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "b94120ac22a8"
down_revision = "a38714b9e23b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invitations",
        sa.Column(
            "title",
            sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invitations", "title")
    # ### end Alembic commands ###
