"""Library default keywords

Revision ID: c587d336f28e
Revises: 01115b529336
Create Date: 2024-06-13 14:24:39.035015

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c587d336f28e"
down_revision = "01115b529336"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE library SET keywords = '{}'::varchar[] WHERE keywords IS NULL")
    op.execute("UPDATE library SET search_keywords = '{}'::varchar[] WHERE search_keywords IS NULL")
    op.alter_column(
        "library",
        "keywords",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False,
        server_default='{}'
    )
    op.alter_column(
        "library",
        "search_keywords",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False,
        server_default='{}'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "library",
        "search_keywords",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    op.alter_column(
        "library",
        "keywords",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    # ### end Alembic commands ###
