"""Drop and update fks activity assignments

Revision ID: 769a83b9c24f
Revises: ce8d525221e9
Create Date: 2024-08-14 13:50:20.256019

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "769a83b9c24f"
down_revision = "ce8d525221e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_activity_assignments_activity_flow_id_flows"), "activity_assignments", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_activity_assignments_activity_id_activities"), "activity_assignments", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_activity_assignments_target_subject_id_subjects"), "activity_assignments", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_activity_assignments_respondent_subject_id_subjects"), "activity_assignments", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_activity_assignments_target_subject_id_subjects"),
        "activity_assignments",
        "subjects",
        ["target_subject_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_activity_assignments_respondent_subject_id_subjects"),
        "activity_assignments",
        "subjects",
        ["respondent_subject_id"],
        ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    op.create_foreign_key(
        op.f("fk_activity_assignments_activity_flow_id_flows"),
        "activity_assignments",
        "flows",
        ["activity_flow_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_activity_assignments_activity_id_activities"),
        "activity_assignments",
        "activities",
        ["activity_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        op.f("fk_activity_assignments_target_subject_id_subjects"), "activity_assignments", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_activity_assignments_respondent_subject_id_subjects"), "activity_assignments", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_activity_assignments_target_subject_id_subjects"),
        "activity_assignments",
        "subjects",
        ["target_subject_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_activity_assignments_respondent_subject_id_subjects"),
        "activity_assignments",
        "subjects",
        ["respondent_subject_id"],
        ["id"],
        ondelete="RESTRICT",
    )
