"""Add new activity assignments

Revision ID: b1f951a8ceac
Revises: 9a1b9e588f49
Create Date: 2024-07-24 14:33:46.426890

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b1f951a8ceac"
down_revision = "9a1b9e588f49"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_assignments",
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("timezone('utc', now())"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("timezone('utc', now())"),
            nullable=True,
        ),
        sa.Column("migrated_date", sa.DateTime(), nullable=True),
        sa.Column("migrated_updated", sa.DateTime(), nullable=True),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("activity_flow_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("activity_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("respondent_subject_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("target_subject_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_flow_id"],
            ["flows.id"],
            name=op.f("fk_activity_assignments_activity_flow_id_flows"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_activity_assignments_activity_id_activities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["respondent_subject_id"],
            ["subjects.id"],
            name=op.f("fk_activity_assignments_respondent_subject_id_subjects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_subject_id"],
            ["subjects.id"],
            name=op.f("fk_activity_assignments_target_subject_id_subjects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_assignments")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity_assignments")
    # ### end Alembic commands ###
