"""Add new field title to user_applet_accesses

Revision ID: f099d463803a
Revises: b94120ac22a8
Create Date: 2024-04-18 17:46:53.094293

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "f099d463803a"
down_revision = "b94120ac22a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_applet_accesses",
        sa.Column(
            "title",
            sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_applet_accesses", "title")
    # ### end Alembic commands ###
