"""Add auto_assign field to activities and flows tables

Revision ID: ce8d525221e9
Revises: b1f951a8ceac
Create Date: 2024-07-18 14:48:04.413317

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ce8d525221e9"
down_revision = "b1f951a8ceac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities", sa.Column("auto_assign", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "activity_histories",
        sa.Column("auto_assign", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "flow_histories", sa.Column("auto_assign", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "flows", sa.Column("auto_assign", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flows", "auto_assign")
    op.drop_column("flow_histories", "auto_assign")
    op.drop_column("activity_histories", "auto_assign")
    op.drop_column("activities", "auto_assign")
    # ### end Alembic commands ###
