"""transfer_from_to_user_id_columns

Revision ID: 54123357967a
Revises: 46f285831ae8
Create Date: 2024-01-30 10:34:58.472907

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "54123357967a"
down_revision = "46f285831ae8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transfer_ownership",
        sa.Column(
            "from_user_id", postgresql.UUID(as_uuid=True), nullable=True
        ),
    )
    op.add_column(
        "transfer_ownership",
        sa.Column("to_user_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_transfer_ownership_to_user_id_users"),
        "transfer_ownership",
        "users",
        ["to_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_transfer_ownership_from_user_id_users"),
        "transfer_ownership",
        "users",
        ["from_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transfer_ownership_from_user_id_users"),
        "transfer_ownership",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_transfer_ownership_to_user_id_users"),
        "transfer_ownership",
        type_="foreignkey",
    )
    op.drop_column("transfer_ownership", "to_user_id")
    op.drop_column("transfer_ownership", "from_user_id")
    # ### end Alembic commands ###
