"""Add type field in Alerts DB

Revision ID: b8fcde7ec10e
Revises: 8498cae0eced
Create Date: 2024-06-26 14:41:06.777376

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b8fcde7ec10e"
down_revision = "8498cae0eced"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alerts", sa.Column("type", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alerts", "type")
    # ### end Alembic commands ###
