"""Add is Prolific Respondant in User

Revision ID: 1e448d205193
Revises: dc2dd9e195d5
Create Date: 2025-01-24 20:55:53.626692

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1e448d205193"
down_revision = "dc2dd9e195d5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_prolific_respondent", sa.Boolean(), server_default="false", nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_prolific_respondent")
    # ### end Alembic commands ###
