"""Add integration_source to SubjectSchema

Revision ID: 11b5cd083450
Revises: 70987d489b17
Create Date: 2025-02-20 17:17:52.052078

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "11b5cd083450"
down_revision = "70987d489b17"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subjects", sa.Column("integration_source", sa.String(length=20), nullable=True, default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subjects", "integration_source")
    # ### end Alembic commands ###
