"""activity_item_history add index

Revision ID: 032d8458aa63
Revises: dc2dd9e195d5
Create Date: 2025-01-22 08:44:42.695477

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "032d8458aa63"
down_revision = "dc2dd9e195d5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_activity_item_histories_activity_id"), "activity_item_histories", ["activity_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_item_histories_activity_id"), table_name="activity_item_histories")
    # ### end Alembic commands ###
