"""Add index on answers_items.answer_id

Revision ID: e6728c9ce215
Revises: 515df3312e1c
Create Date: 2026-02-27 09:20:47.489895

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e6728c9ce215"
down_revision = "515df3312e1c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ml_loris_user_relationship")
    op.drop_table("applet_events_cleanup")
    op.drop_index(op.f("uq_activity_assignments_activity_flow_respondent_target"), table_name="activity_assignments")
    op.drop_index(op.f("uq_activity_assignments_activity_respondent_target"), table_name="activity_assignments")
    op.drop_table("activity_assignments")
    op.drop_table("activity_events")
    op.drop_table("user_events")
    op.drop_table("flow_events")
    op.drop_table("periodicity")
    op.drop_constraint(op.f("fk_alerts_subject_id_subjects"), "alerts", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_alerts_subject_id_subjects"), "alerts", "subjects", ["subject_id"], ["id"], ondelete="RESTRICT"
    )
    op.alter_column(
        "answers", "applet_history_id", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False
    )
    op.alter_column("answers", "flow_history_id", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True)
    op.alter_column(
        "answers", "activity_history_id", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False
    )
    op.create_index(op.f("ix_answers_device_id"), "answers", ["device_id"], unique=False)
    op.create_index(op.f("ix_answers_event_history_id"), "answers", ["event_history_id"], unique=False)
    op.drop_constraint(op.f("answers_ehr_submit_activity_key"), "answers_ehr", type_="unique")
    op.drop_index(op.f("ix_answers_ehr_submit_activity_id"), table_name="answers_ehr")
    op.create_index(op.f("ix_answers_ehr_activity_id"), "answers_ehr", ["activity_id"], unique=False)
    op.create_index(op.f("ix_answers_ehr_submit_id"), "answers_ehr", ["submit_id"], unique=False)
    op.create_index(op.f("ix_answers_items_answer_id"), "answers_items", ["answer_id"], unique=False)
    op.drop_constraint(op.f("fk_applet_events_event_id_event_histories"), "applet_events", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_applet_events_event_id_event_histories"),
        "applet_events",
        "event_histories",
        ["event_id"],
        ["id_version"],
        ondelete="CASCADE",
    )
    op.alter_column("event_histories", "version", existing_type=sa.VARCHAR(length=13), nullable=True)
    op.alter_column("event_histories", "periodicity", existing_type=sa.VARCHAR(length=10), nullable=True)
    op.alter_column(
        "events",
        "version",
        existing_type=sa.VARCHAR(length=13),
        nullable=True,
        existing_server_default=sa.text("(to_char(timezone('utc'::text, now()), 'YYYYMMDD'::text) || '-1'::text)"),
    )
    op.alter_column("events", "periodicity", existing_type=sa.VARCHAR(length=10), nullable=True)
    op.drop_column("events", "periodicity_id")
    op.drop_constraint(
        op.f("fk_notification_histories_event_id_event_histories"), "notification_histories", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_notification_histories_event_id_event_histories"),
        "notification_histories",
        "event_histories",
        ["event_id"],
        ["id_version"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(op.f("fk_notifications_event_id_events"), "notifications", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_notifications_event_id_events"), "notifications", "events", ["event_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("fk_reminder_histories_event_id_event_histories"), "reminder_histories", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_reminder_histories_event_id_event_histories"),
        "reminder_histories",
        "event_histories",
        ["event_id"],
        ["id_version"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(op.f("fk_reminders_event_id_events"), "reminders", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_reminders_event_id_events"), "reminders", "events", ["event_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("fk_subject_relations_source_subject_id_subjects"), "subject_relations", type_="foreignkey")
    op.drop_constraint(op.f("fk_subject_relations_target_subject_id_subjects"), "subject_relations", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_subject_relations_target_subject_id_subjects"),
        "subject_relations",
        "subjects",
        ["target_subject_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_subject_relations_source_subject_id_subjects"),
        "subject_relations",
        "subjects",
        ["source_subject_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.alter_column("subjects", "is_deleted", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "subjects", "language", existing_type=sa.VARCHAR(length=20), type_=sa.String(length=5), existing_nullable=True
    )
    op.drop_index(op.f("idx_subjects_meta"), table_name="subjects", postgresql_using="gin")
    op.drop_column("subjects", "is_deleted_null")
    op.alter_column(
        "token_blacklist",
        "type",
        existing_type=postgresql.ENUM("ACCESS", "REFRESH", name="token_purpose"),
        type_=sa.Enum("ACCESS", "REFRESH", "MFA", "DOWNLOAD_RECOVERY_CODES", name="tokenpurpose"),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("fk_user_pins_pinned_subject_id_subjects"), "user_pins", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_user_pins_pinned_subject_id_subjects"),
        "user_pins",
        "subjects",
        ["pinned_subject_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=100), type_=sa.String(length=56), existing_nullable=True
    )
    op.alter_column(
        "users", "mfa_enabled", existing_type=sa.BOOLEAN(), nullable=True, existing_server_default=sa.text("false")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "mfa_enabled", existing_type=sa.BOOLEAN(), nullable=False, existing_server_default=sa.text("false")
    )
    op.alter_column(
        "users", "email", existing_type=sa.String(length=56), type_=sa.VARCHAR(length=100), existing_nullable=True
    )
    op.drop_constraint(op.f("fk_user_pins_pinned_subject_id_subjects"), "user_pins", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_user_pins_pinned_subject_id_subjects"),
        "user_pins",
        "subjects",
        ["pinned_subject_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "token_blacklist",
        "type",
        existing_type=sa.Enum("ACCESS", "REFRESH", "MFA", "DOWNLOAD_RECOVERY_CODES", name="tokenpurpose"),
        type_=postgresql.ENUM("ACCESS", "REFRESH", name="token_purpose"),
        existing_nullable=False,
    )
    op.add_column(
        "subjects",
        sa.Column(
            "is_deleted_null", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False
        ),
    )
    op.create_index(op.f("idx_subjects_meta"), "subjects", ["meta"], unique=False, postgresql_using="gin")
    op.alter_column(
        "subjects", "language", existing_type=sa.String(length=5), type_=sa.VARCHAR(length=20), existing_nullable=True
    )
    op.alter_column("subjects", "is_deleted", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_constraint(op.f("fk_subject_relations_source_subject_id_subjects"), "subject_relations", type_="foreignkey")
    op.drop_constraint(op.f("fk_subject_relations_target_subject_id_subjects"), "subject_relations", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_subject_relations_target_subject_id_subjects"),
        "subject_relations",
        "subjects",
        ["target_subject_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_subject_relations_source_subject_id_subjects"),
        "subject_relations",
        "subjects",
        ["source_subject_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.drop_constraint(op.f("fk_reminders_event_id_events"), "reminders", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_reminders_event_id_events"),
        "reminders",
        "events",
        ["event_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("fk_reminder_histories_event_id_event_histories"), "reminder_histories", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_reminder_histories_event_id_event_histories"),
        "reminder_histories",
        "event_histories",
        ["event_id"],
        ["id_version"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.drop_constraint(op.f("fk_notifications_event_id_events"), "notifications", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_notifications_event_id_events"),
        "notifications",
        "events",
        ["event_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_notification_histories_event_id_event_histories"), "notification_histories", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_notification_histories_event_id_event_histories"),
        "notification_histories",
        "event_histories",
        ["event_id"],
        ["id_version"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.add_column(
        "events",
        sa.Column(
            "periodicity_id",
            postgresql.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column("events", "periodicity", existing_type=sa.VARCHAR(length=10), nullable=False)
    op.alter_column(
        "events",
        "version",
        existing_type=sa.VARCHAR(length=13),
        nullable=False,
        existing_server_default=sa.text("(to_char(timezone('utc'::text, now()), 'YYYYMMDD'::text) || '-1'::text)"),
    )
    op.alter_column("event_histories", "periodicity", existing_type=sa.VARCHAR(length=10), nullable=False)
    op.alter_column("event_histories", "version", existing_type=sa.VARCHAR(length=13), nullable=False)
    op.drop_constraint(op.f("fk_applet_events_event_id_event_histories"), "applet_events", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_applet_events_event_id_event_histories"),
        "applet_events",
        "event_histories",
        ["event_id"],
        ["id_version"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_answers_items_answer_id"), table_name="answers_items")
    op.drop_index(op.f("ix_answers_ehr_submit_id"), table_name="answers_ehr")
    op.drop_index(op.f("ix_answers_ehr_activity_id"), table_name="answers_ehr")
    op.create_index(
        op.f("ix_answers_ehr_submit_activity_id"), "answers_ehr", ["submit_id", "activity_id"], unique=False
    )
    op.create_unique_constraint(op.f("answers_ehr_submit_activity_key"), "answers_ehr", ["submit_id", "activity_id"])
    op.drop_index(op.f("ix_answers_event_history_id"), table_name="answers")
    op.drop_index(op.f("ix_answers_device_id"), table_name="answers")
    op.alter_column(
        "answers", "activity_history_id", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False
    )
    op.alter_column("answers", "flow_history_id", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True)
    op.alter_column(
        "answers", "applet_history_id", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False
    )
    op.drop_constraint(op.f("fk_alerts_subject_id_subjects"), "alerts", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_alerts_subject_id_subjects"),
        "alerts",
        "subjects",
        ["subject_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.create_table(
        "periodicity",
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("type", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("selected_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("migrated_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("migrated_updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_periodicity")),
    )
    op.create_table(
        "flow_events",
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("flow_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("event_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("migrated_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("migrated_updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_flow_events_event_id_events"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flow_events")),
        sa.UniqueConstraint("flow_id", "event_id", "is_deleted", name=op.f("_unique_flow_events")),
    )
    op.create_table(
        "user_events",
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("event_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("migrated_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("migrated_updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_user_events_event_id_events"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_events_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_events")),
        sa.UniqueConstraint("user_id", "event_id", "is_deleted", name=op.f("_unique_user_events")),
    )
    op.create_table(
        "activity_events",
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("activity_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("event_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("migrated_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("migrated_updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_activity_events_event_id_events"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_events")),
        sa.UniqueConstraint("activity_id", "event_id", "is_deleted", name=op.f("_unique_activity_events")),
    )
    op.create_table(
        "activity_assignments",
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("migrated_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("migrated_updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("activity_flow_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("activity_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("respondent_subject_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("target_subject_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["respondent_subject_id"],
            ["subjects.id"],
            name=op.f("fk_activity_assignments_respondent_subject_id_subjects"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_subject_id"],
            ["subjects.id"],
            name=op.f("fk_activity_assignments_target_subject_id_subjects"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_assignments")),
    )
    op.create_index(
        op.f("uq_activity_assignments_activity_respondent_target"),
        "activity_assignments",
        ["activity_id", "respondent_subject_id", "target_subject_id"],
        unique=True,
    )
    op.create_index(
        op.f("uq_activity_assignments_activity_flow_respondent_target"),
        "activity_assignments",
        ["activity_flow_id", "respondent_subject_id", "target_subject_id"],
        unique=True,
    )
    op.create_table(
        "applet_events_cleanup",
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("migrated_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("migrated_updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("applet_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("event_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applet_events_cleanup")),
        sa.UniqueConstraint("applet_id", "event_id", "is_deleted", name=op.f("_unique_applet_events_cleanup")),
    )
    op.create_table(
        "ml_loris_user_relationship",
        sa.Column(
            "id", postgresql.UUID(), server_default=sa.text("gen_random_uuid()"), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("migrated_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("migrated_updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("ml_user_uuid", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("loris_user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("ml_user_uuid", name=op.f("pk_ml_loris_user_relationship")),
        sa.UniqueConstraint("loris_user_id", name=op.f("uq_ml_loris_user_relationship_loris_user_id")),
    )
    # ### end Alembic commands ###
