"""add assessment activity version id on answers item

Revision ID: 60528d410fd1
Revises: 8c59c7363c67
Create Date: 2023-11-13 19:55:57.797942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "60528d410fd1"
down_revision = "8c59c7363c67"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "answers_items",
        sa.Column("assessment_activity_id", sa.Text(), nullable=True),
    )
    op.create_index(
        op.f("ix_answers_items_assessment_activity_id"),
        "answers_items",
        ["assessment_activity_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_answers_items_assessment_activity_id"),
        table_name="answers_items",
    )
    op.drop_column("answers_items", "assessment_activity_id")
    # ### end Alembic commands ###
