name: Check code quality
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: "awslabs/git-secrets"
          ref: "master"
      - name: Install git-secrets
        run: sudo make install
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install git-secrets in the repository
        run: git secrets --install
      - name: Install git-secrets aws register in the repository
        run: git secrets --register-aws
      - name: Scan aws secrets
        run: git secrets --scan
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: uv sync --locked
      - name: Check formatting
        run: uv run ruff check . && uv run ruff format --check .
      - name: Check types
        run: uv run mypy ./
