name: Check code quality
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "awslabs/git-secrets"
          ref: "master"
      - name: Install git-secrets
        run: sudo make install
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install git-secrets in the repository
        run: git secrets --install
      - name: Install git-secrets aws register in the repository
        run: git secrets --register-aws
      - name: Scan aws secrets
        run: git secrets --scan
      - name: Install pipenv
        run: python -m pip install --upgrade pip && pip install pipenv
      - name: Install deps
        run: pipenv sync --system --dev
      - name: Check formatting
        run: ruff check . && ruff format --check .
      - name: Check types
        run: mypy ./
