name: Coverage
on: [push]

permissions:
  statuses: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.23.3'

      - name: "Get coverage"
        run: |
          cp .env.default .env
          echo -e "\nRABBITMQ__USE_SSL=False" >> .env
          ls
          pwd
          make run_local

      - run: make ctest

      - run: make creport SHA=${{ github.sha }}

      - run: ls

      - run: pip install smokeshow

      - run: smokeshow upload htmlcov
        env:
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Coverage {coverage-percentage}
          SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 80
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.FASTAPI_SMOKESHOW_UPLOAD }}
          SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
          SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}
          