name: E2E Tests

on:
  workflow_call:
    inputs:
      service-url:
        type: string
        description: Service URL endpoint
        required: true
    outputs:
      report-url:
        description: URL of the test report
        value: ${{ jobs.publish-report.outputs.report-url }}

env:
  AWS_REGION: us-east-1

jobs:
  run-e2e-tests:
    name: Run E2E Test Suite
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      discussions: write

    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::917902836630:role/cmiml-devops-oidc-github-role
          role-session-name: OIDC-GHA-session
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/checkout@v4
        name: Checkout
        with:
          repository: ChildMindInstitute/MindLogger-TAF
          # Matching deploy key in TAF repo
          ssh-key: ${{ secrets.TAF_PRIVATE_KEY }}
          ref: release
      - name: Install
        run: npm install
      - name: Setup Environment
        run: |
          sed -i 's/API_DOMAIN.*//' .env ;
          echo 'API_DOMAIN=${{ inputs.service-url }}' >> .env
      - name: Validate Environment
        run: cat .env
      - name: Get Secrets by Name and by ARN
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            taf/dev
          parse-json-secrets: true

      - name: Run tests
        run: npm run test:api
        continue-on-error: true
        id: e2e-tests

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST_RESULTS }}
          SLACK_USERNAME: GithubActions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_COLOR: ${{ steps.e2e-tests.outcome }}
          SLACK_MESSAGE_ON_SUCCESS: "E2E tests succeeded"
          SLACK_MESSAGE_ON_FAILURE: "E2E tests failed"
          MSG_MINIMAL: actions url


      - name: Collect artifacts
        uses: actions/upload-artifact@v4
        with:
          name: e2e-results
          path: test-results/api
          if-no-files-found: error

      - name: Fail if tests failed
        if: steps.e2e-tests.outcome != 'success'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Unit/Int tests failed')

  publish-report:
    name: Publish Report
    needs: [ run-e2e-tests ]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          ref: gh-pages
          path: gh-pages

      - name: Fetch results
        uses: actions/download-artifact@v4
        with:
          name: e2e-results
          path: test-results/api

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: test-results/api
          gh_pages: gh-pages
          allure_history: allure-history-e2e
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
      - name: Generate Report URL
        if: always()
        id: report-url
        uses: actions/github-script@v3
        with:
          script: |
            core.setOutput('report-url', 'https://childmindinstitute.github.io/preview-app-demo/${{ github.run_number }}')
    outputs:
      report-url: ${{ steps.report-url.outputs.report-url }}