name: Testing Build and Deploy
on:
  push:
    branches:
      - "M2-8819-Deployment-Improvement-Have-migrations-run-automatically-in-a-separate-task-on-DEV"
  workflow_dispatch: {}
permissions:
  id-token: write
  contents: read
  issues: write


jobs:
  build:
    name: Docker Build and Push
    secrets: inherit
    uses: ./.github/workflows/_build.yaml


  deploy-dev:
    name: Deploy to Dev
    needs: [build]
    secrets: inherit
    uses: ./.github/workflows/_deploy.yaml
    with:
      image-tag: latest
      env-name: dev

