name: Preview and Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
#  push:
#    branches:
#      - "feature/**"

# Only run the latest.  Cancel old runs in progress.
concurrency:
  cancel-in-progress: true
  group: "preview-env-manage-${{ github.event.number }}"

env:
  APP_NAME: ${{ github.event.repository.name }}
  VPC_ID: vpc-0a83201b71e854abd
  COPILOT_SERVICE: mindlogger-backend
  AWS_REGION: us-east-1

jobs:

  create-database:
    name: Create preview env DB
    uses: ./.github/workflows/create_db.yaml
    with:
      db-name: "mindlogger_backend_pr_${{ github.event.number }}"
    secrets: inherit

  create-preview-env:
    needs: [create-database]
    uses: ./.github/workflows/create-preview-env.yaml
    with:
      env-name: "pr-${{ github.event.number }}"
      env-snake-name: "pr_${{ github.event.number }}"
      app-name: ${{ github.event.repository.name }}
      vpc-id: vpc-0a83201b71e854abd
      copilot-service: mindlogger-backend
    secrets: inherit

  comment-create-preview-env:
    name: Comment on preview env
    runs-on: ubuntu-latest
    needs: [create-preview-env]
    if: ${{ always() }}
    steps:
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          message: |
            :arrow_right: Preview environment created: [Click Me!](${{ needs.create-preview-env.outupts.service-url }})
          reactions: eyes, rocket
          comment_tag: service-url

  run-unit-tests:
    uses: ./.github/workflows/tests.yaml
    secrets: inherit

  comment-tests:
    name: Comment on unit test outcome
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [run-unit-tests]
    steps:
      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.PAT_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: ${{ needs.run-unit-tests.outputs.report-url }}


  run-e2e-tests:
    name: Run E2E Test Suite
    needs: [ create-preview-env, run-unit-tests ]
    if: ${{ always() && needs.run-unit-tests.result == 'success' && needs.create-preview-env.result == 'success' }}
    uses: ./.github/workflows/e2e-tests.yaml
    secrets: inherit
    with:
      service-url: ${{ needs.create-preview-env.outputs.service-url }}

  comment-e2e-tests:
    name: Comment on test outcome
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [run-e2e-tests]
    steps:
      - name: Comment on PR with test success
        if: ${{ needs.run-e2e-tests.outcome == 'success' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :white_check_mark: Unit/Integration tests passed!
          comment_tag: taf-results
      - name: Comment on PR with test failure
        if: ${{ needs.run-e2e-tests.outcome != 'success' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :x: Integration tests failed
          comment_tag: taf-results

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: ${{ needs.run-e2e-tests.outputs.report-url }}
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: ${{ needs.run-e2e-tests.outputs.report-url }}

