name: Preview and Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
#  push:
#    branches:
#      - "feature/**"

# Only run the latest.  Cancel old runs in progress.
concurrency:
  cancel-in-progress: true
  group: "preview-env-manage-${{ github.ref_name }}"

env:
  APP_NAME: ${{ github.event.repository.name }}
  VPC_ID: vpc-0a83201b71e854abd
  COPILOT_SERVICE: mindlogger-backend
  AWS_REGION: us-east-1

jobs:
  create-preview-env:
    uses: ./.github/workflows/create-preview-env.yaml
    with:
      env-name: "pr-${{ github.event.number }}"
      env-snake-name: "pr_${{ github.event.number }}"
      app-name: ${{ github.event.repository.name }}
      vpc-id: vpc-0a83201b71e854abd
      copilot-service: mindlogger-backend
    secrets: inherit

  run-unit-tests:
    uses: ./.github/workflows/tests.yaml
    secrets: inherit

  create-database:
    needs: [create-preview-env]
    name: Create preview env DB
    uses: ./.github/workflows/create_db.yaml
    with:
      db-name: "mindlogger_backend_pr_${{ github.event.number }}"
    secrets: inherit

  run-e2e-tests:
    name: Run E2E Test Suite
    needs: [ create-preview-env, run-unit-tests ]
    if: ${{ always() && needs.run-unit-tests.result == 'success' && needs.create-preview-env.result == 'success' }}
    uses: ./.github/workflows/e2e-tests.yaml
    secrets: inherit
    with:
      service-url: ${{ needs.create-preview-env.outputs.service-url }}

  publish-report:
    name: Publish Report
    needs: [run-e2e-tests]
    if: ${{ always() && github.event_name == 'pull_request' && (needs.run-int-tests.result == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          ref: gh-pages
          path: gh-pages

      - name: Fetch results
        uses: actions/download-artifact@v4
        with:
          name: taf-results
          path: test-results/api

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: test-results/api
          gh_pages: gh-pages
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: https://childmindinstitute.github.io/preview-app-demo/${{ github.run_number }}

