name: Preview and Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
#  push:
#    branches:
#      - "feature/**"

# Only run the latest.  Cancel old runs in progress.
concurrency:
  cancel-in-progress: true
  group: "preview-env-manage-${{ github.event.number }}"

env:
  APP_NAME: ${{ github.event.repository.name }}
  VPC_ID: vpc-0a83201b71e854abd
  COPILOT_SERVICE: mindlogger-backend
  AWS_REGION: us-east-1

jobs:

  create-database:
    name: Create preview env DB
    uses: ./.github/workflows/create_db.yaml
    with:
      db-name: "mindlogger_backend_pr_${{ github.event.number }}"
    secrets: inherit

  create-preview-env:
    needs: [create-database]
    uses: ./.github/workflows/create-preview-env.yaml
    with:
      env-name: "pr-${{ github.event.number }}"
      env-snake-name: "pr_${{ github.event.number }}"
      app-name: ${{ github.event.repository.name }}
      vpc-id: vpc-0a83201b71e854abd
      copilot-service: mindlogger-backend
    secrets: inherit

  run-unit-tests:
    uses: ./.github/workflows/tests.yaml
    secrets: inherit

  run-e2e-tests:
    name: Run E2E Test Suite
    needs: [ create-preview-env, run-unit-tests ]
    if: ${{ always() && needs.run-unit-tests.result == 'success' && needs.create-preview-env.result == 'success' }}
    uses: ./.github/workflows/e2e-tests.yaml
    secrets: inherit
    with:
      service-url: ${{ needs.create-preview-env.outputs.service-url }}



  publish-report:
    name: Publish Report
    needs: [run-e2e-tests]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST_RESULTS }}
          SLACK_USERNAME: GithubActions
          SLACK_ICON: https://cdn-icons-png.flaticon.com/128/2111/2111432.png
          SLACK_COLOR: ${{ needs.run-e2e-tests.outcome }}
      - name: Comment on PR with test success
        if: ${{ needs.run-e2e-tests.outcome == 'success' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :white_check_mark: Unit/Integration tests passed!
          comment_tag: taf-results
      - name: Comment on PR with test failure
        if: ${{ needs.run-e2e-tests.outcome != 'success' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :x: Integration tests failed
          comment_tag: taf-results

      - uses: actions/checkout@v4
        name: Checkout
        with:
          ref: gh-pages
          path: gh-pages

      - name: Fetch results
        uses: actions/download-artifact@v4
        with:
          name: taf-results
          path: test-results/api

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: test-results/api
          gh_pages: gh-pages
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: ${{ needs.run-e2e-tests.outcome }}
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: https://childmindinstitute.github.io/preview-app-demo/${{ github.run_number }}

