
name: Build and Deploy
on:
  push:
    branches:
      - develop
#      - "M2-8819-Deployment-Improvement-Have-migrations-run-automatically-in-a-separate-task-on-DEV"
#  pull_request:
#    types:
#      - opened
#      - synchronize
#    branches:
#      - "M2-8819-Deployment-Improvement-Have-migrations-run-automatically-in-a-separate-task-on-DEV"
  workflow_dispatch: {}


concurrency:
  cancel-in-progress: true
  group: api-build

permissions:
  id-token: write
  contents: read
  issues: write

env:
  GITHUB_ORGANIZATION: ${{ github.repository_owner }}
  GITHUB_REPO_NAME: ${{ github.event.repository.name }}
  GITHUB_BRANCH_OR_TAG: ${{ github.ref_name }}
  GITHUB_REF: ${{ github.ref }}
  BUILD_NAME: ${{github.event_name}}
  BUILD_NUMBER: ${{github.run_id}}
  ECR_ADDRESS: 917902836630.dkr.ecr.us-east-1.amazonaws.com
  DR_ECR_ADDRESS: 973422231492.dkr.ecr.us-west-2.amazonaws.com
  OUT_DIR: ./out
  AWS_REGION : "us-east-1"
  DR_AWS_REGION : "us-west-2"
  ECR_REPO: 917902836630.dkr.ecr.us-east-1.amazonaws.com/api-server
  DR_ECR_REPO: 973422231492.dkr.ecr.us-west-2.amazonaws.com/api-server


jobs:
  build:
    name: Docker Build and Push
    uses: ./.github/workflows/_build.yaml
#    outputs:
#      image-name: ${{ steps.sha.outputs.IMAGE_NAME }}
#      image-sha: ${{ steps.sha.outputs.SHORT_SHA }}
#      ecr-repo: ${{ env.ECR_REPO }}


  deploy-dev:
    name: Deploy to Dev
    needs: [build]
#    environment: dev
    #if: ${{ github.event.pull_request.merged }}
#    uses: ./.github/workflows/run_deploy_dev.yaml
    uses: ./.github/workflows/_deploy.yaml
    with:
      image: ${{ needs.build.outputs.ecr-repo }}
      image-tag: latest
      env-name: dev

#  deploy_to_uat:
#    needs: build_job
#    uses: ./.github/workflows/run_deploy_uat.yaml
#    with:
#      COMMIT_HASH: ${{ github.sha }}
#      IMAGE_NAME: ${{ needs.build_job.outputs.IMAGE_NAME }}
#
#  deploy_to_test:
#    needs: build_job
#    uses: ChildMindInstitute/mindlogger-backend-refactor/.github/workflows/run_deploy_test.yaml@develop
#    with:
#      COMMIT_HASH: ${{ github.sha }}
#      IMAGE_PREFIX: ${{ github.ref_name }}
