
name: Build and Deploy
on:
  push:
    branches:
      - develop
  workflow_dispatch: {}


concurrency:
  cancel-in-progress: false
  group: api-build-deploy

permissions:
  id-token: write
  contents: read
  issues: write

env:
  GITHUB_ORGANIZATION: ${{ github.repository_owner }}
  GITHUB_REPO_NAME: ${{ github.event.repository.name }}
  GITHUB_BRANCH_OR_TAG: ${{ github.ref_name }}
  GITHUB_REF: ${{ github.ref }}
  BUILD_NAME: ${{github.event_name}}
  BUILD_NUMBER: ${{github.run_id}}
  ECR_ADDRESS: 917902836630.dkr.ecr.us-east-1.amazonaws.com
  DR_ECR_ADDRESS: 973422231492.dkr.ecr.us-west-2.amazonaws.com
  OUT_DIR: ./out
  AWS_REGION : "us-east-1"
  DR_AWS_REGION : "us-west-2"
  ECR_REPO: 917902836630.dkr.ecr.us-east-1.amazonaws.com/api-server
  DR_ECR_REPO: 973422231492.dkr.ecr.us-west-2.amazonaws.com/api-server


jobs:
  build:
    name: Docker Build and Push
    secrets: inherit
    uses: ./.github/workflows/_build.yaml


  deploy-dev:
    name: Deploy to Dev
    needs: [ build ]
    secrets: inherit
    uses: ./.github/workflows/_deploy.yaml
    with:
      image-tag: latest
      env-name: dev

  run-e2e-tests:
    name: Run E2E Test Suite
    needs: [ deploy-dev ]
    if: ${{ !cancelled() && needs.deploy-dev.result == 'success' }}
    uses: ChildMindInstitute/mindlogger-backend-refactor/.github/workflows/e2e-tests.yaml@develop
    secrets: inherit
    permissions:
      contents: write
    with:
      service-url: https://api-dev.cmiml.net

  comment-e2e-tests:
    name: Comment on test outcome
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      statuses: write
    needs: [run-e2e-tests]
    steps:
      - name: "Send Slack message on failure"
        if: ${{ needs.run-e2e-tests.result != 'success' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: failure
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST_RESULTS }}
          SLACKIFY_MARKDOWN: true
          SLACK_TITLE: |
            :rotating_light: E2E test suite failed
          SLACK_MESSAGE: >-
            E2E tests for dev failed in ${{ github.repository }}
            \n\n
            :arrow_right: [Action Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            \n\n
            :label: [Commit](${{ github.event.head_commit.url }}) | :chart_with_upwards_trend: [Test Report](${{ needs.run-e2e-tests.outputs.report-url }})
          SLACK_ICON: https://github.com/github.png?size=48
          MSG_MINIMAL: true


      - name: Post the link to the report
        if: ${{ !cancelled() }}
        uses: guibranco/github-status-action-v2@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'E2E Test report'
          state: ${{ needs.run-e2e-tests.result }}
          sha: ${{ github.head_ref }}
          target_url: ${{ needs.run-e2e-tests.outputs.report-url }}



#  deploy_to_uat:
#    needs: build_job
#    uses: ./.github/workflows/run_deploy_uat.yaml
#    with:
#      COMMIT_HASH: ${{ github.sha }}
#      IMAGE_NAME: ${{ needs.build_job.outputs.IMAGE_NAME }}
#
#  deploy_to_test:
#    needs: build_job
#    uses: ChildMindInstitute/mindlogger-backend-refactor/.github/workflows/run_deploy_test.yaml@develop
#    with:
#      COMMIT_HASH: ${{ github.sha }}
#      IMAGE_PREFIX: ${{ github.ref_name }}
