name: Run TAF API tests

on: 
  - push

jobs:
  taf_api_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Chrome
      run: |
        curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb http://dl.google.com/linux/chrome/deb/ stable main" || sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get -y update
        sudo apt-get -y install google-chrome-stable
        sudo ln -s /usr/bin/google-chrome /usr/bin/chrome
        google-chrome --version && which google-chrome

    - name: Checkout tests repository
      uses: actions/checkout@v4
      with:
        repository: ChildMindInstitute/MindLogger-TAF
        path: 'taf_api_tests'
        token: ${{ secrets.PAT_TOKEN }}

    - name: Get variables from AWS Secrets Manager
      env:
        ENV_NAME: ${{ secrets.TAF_TARGET }} # dev | test | stage | uat
        SECRET_ID: ${{ secrets.TAF_SECRET_ID }} # AWS Secrets Manager - Secret ID
      run: |
        aws --version
        API_DOMAIN=$(aws secretsmanager get-secret-value --secret-id ${SECRET_ID}/${ENV_NAME} --query SecretString --output text | jq -r .API_DOMAIN)
        REPORT_SERVER_IP=$(aws secretsmanager get-secret-value --secret-id ${SECRET_ID}/${ENV_NAME} --query SecretString --output text | jq -r .REPORT_SERVER_IP)
        WEB_APP_BASE_URL=$(aws secretsmanager get-secret-value --secret-id ${SECRET_ID}/${ENV_NAME} --query SecretString --output text | jq -r .WEB_APP_BASE_URL)
        ADMIN_APP_BASE_URL=$(aws secretsmanager get-secret-value --secret-id ${SECRET_ID}/${ENV_NAME} --query SecretString --output text | jq -r .ADMIN_APP_BASE_URL)

        echo "API_DOMAIN=${API_DOMAIN}"
        echo "REPORT_SERVER_IP=${REPORT_SERVER_IP}"
        echo "WEB_APP_BASE_URL=${WEB_APP_BASE_URL}"
        echo "ADMIN_APP_BASE_URL=${ADMIN_APP_BASE_URL}"

        REGULAR_DB_CONNECTION_STRING=$(aws secretsmanager get-secret-value --secret-id ${SECRET_ID}/${ENV_NAME} --query SecretString --output text | jq -r .REGULAR_DB_CONNECTION_STRING)
        ARBITRARY_DB_CONNECTION_STRING=$(aws secretsmanager get-secret-value --secret-id ${SECRET_ID}/${ENV_NAME} --query SecretString --output text | jq -r .ARBITRARY_DB_CONNECTION_STRING)
        MAILINATOR_TOKEN=$(aws secretsmanager get-secret-value --secret-id ${SECRET_ID}/${ENV_NAME} --query SecretString --output text | jq -r .MAILINATOR_TOKEN)

    - name: Run TAF API tests
      env:
        HEADLESS: 'true'
        BROWSER_NAME: 'chrome'
      run: |
        cd taf_api_tests
        npm install
        npm run test:api

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.taf_api_tests.result == 'failure' || needs.taf_api_tests.result == 'timed_out') }}
    needs:
      - taf_api_tests
    steps:
      - uses: actions/checkout@v4
      - name: "Send Slack message on failure"
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: failure
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_TEST_WORKFLOW }}
          SLACK_TITLE: TAF API tests
          SLACK_MESSAGE: 'TAF API tests failed!'
  
  on-success:
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.taf_api_tests.result == 'success') }}
    needs:
      - taf_api_tests
    steps:
      - uses: actions/checkout@v4
      - name: "Send Slack message on success"
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: success
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_TEST_WORKFLOW }}
          SLACK_TITLE: TAF API tests
          SLACK_MESSAGE: 'TAF API tests passed.'
