name: Run TAF API tests

on: 
  - push

env:
  AWS_REGION: 'us-east-1'
  ENV_NAME: ${{ vars.TAF_TARGET }} # dev | test | stage | uat

jobs:
  taf_api_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout tests repository
      uses: actions/checkout@v4
      with:
        repository: ChildMindInstitute/MindLogger-TAF
        path: 'taf_api_tests'
        token: ${{ secrets.PAT_TOKEN }}

    - name: Run TAF API tests
      run: |
        API_DOMAIN=admin-${ENV_NAME}.cmiml.net
        REPORT_SERVER_IP=report-server-${ENV_NAME}.cmiml.net
        WEB_APP_BASE_URL=web-${ENV_NAME}.cmiml.net
        ADMIN_APP_BASE_URL=admin-${ENV_NAME}.cmiml.net

        cd taf_api_tests
        npm install
#        npm run test:api

    - name: Test results
      id: test_results
      run: |
#        echo $(sed -n '2p' test-results/api/test-results.xml | grep -oP 'time="\d+\.\d+" tests="\d+" failures="\d+" skipped="\d+"') >> "$GITHUB_OUTPUT"
        echo "11 failed 1 skipped" >> "$GITHUB_OUTPUT"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.taf_api_tests.result == 'failure' || needs.taf_api_tests.result == 'timed_out') }}
    needs:
      - taf_api_tests
    steps:
      - uses: actions/checkout@v4
      - name: "Send Slack message on failure"
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: failure
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_TEST_WORKFLOW }}
          SLACK_TITLE: TAF API tests
          SLACK_MESSAGE: "TAF API tests failed! ${{ steps.test_results.outputs.result }}"
  
  on-success:
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.taf_api_tests.result == 'success') }}
    needs:
      - taf_api_tests
    steps:
      - uses: actions/checkout@v4
      - name: "Send Slack message on success"
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: success
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL_TEST_WORKFLOW }}
          SLACK_TITLE: TAF API tests
          SLACK_MESSAGE: 'TAF API tests passed.'
