name: Automated tests
on: [pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.23.3'
      - name: "Running tests"
        run: |
          cp .env.default .env
          docker compose up -d
          make dtest
